my-lang: ml::BatchTokenizer Class Reference
ml::BatchTokenizer Class Reference
High-performance batch tokenization for large sources.
#include <Lexer.hpp>
Public Member Functions
BatchTokenizer (StringInterner &interner, DiagnosticManager &diagMgr, const LexerOptions &opts=LexerOptions{})
std::vector< std::vector< Token > > tokenizeParallel (const std::vector< std::string_view > &sources)
Tokenize multiple sources in parallel (if supported)
void tokenizeStreaming (std::string_view source, std::function< void(const Token &)> callback)
Tokenize with streaming support for very large files.
LexerStats getAggregateStats () const
Get aggregate statistics from all tokenization operations.
Detailed Description
High-performance batch tokenization for large sources.
Definition at line 306 of file Lexer.hpp.
Constructor & Destructor Documentation
BatchTokenizer()
ml::BatchTokenizer::BatchTokenizer (StringInterner & interner, DiagnosticManager & diagMgr, const LexerOptions & opts = LexerOptions{})
Definition at line 1553 of file Lexer.cpp.
Member Function Documentation
getAggregateStats()
LexerStats ml::BatchTokenizer::getAggregateStats () const inline
Get aggregate statistics from all tokenization operations.
Definition at line 320 of file Lexer.hpp.
tokenizeParallel()
std::vector< std::vector< Token > > ml::BatchTokenizer::tokenizeParallel (const std::vector< std::string_view > & sources)
Tokenize multiple sources in parallel (if supported)
Definition at line 1559 of file Lexer.cpp.
References ml::tokenizeString().
tokenizeStreaming()
void ml::BatchTokenizer::tokenizeStreaming (std::string_view source, std::function< void(const Token &)> callback)
Tokenize with streaming support for very large files.
Definition at line 1574 of file Lexer.cpp.
References ml::LexerStats::branchMisses, ml::LexerStats::characterCount, ml::LexerStats::commentCount, ml::EndOfFile, ml::Token::getKind(), ml::Lexer::getStats(), ml::LexerStats::identifierCount, ml::LexerStats::keywordCount, ml::LexerStats::lexingTimeMs, ml::LexerStats::lineCount, ml::LexerStats::literalCount, ml::LexerStats::lookupTableHits, ml::Lexer::nextToken(), ml::LexerStats::simdOperations, ml::LexerStats::tokenCount, and ml::LexerStats::updateAverages().
The documentation for this class was generated from the following files:
include/ml/Parse/Lexer.hpp
src/Parse/Lexer.cpp