my-lang: ml::DiagnosticSuppressor Class Reference
ml::DiagnosticSuppressor Class Reference
RAII helper for suppressing diagnostics in a scope.
#include <DiagnosticManager.hpp>
Public Member Functions
DiagnosticSuppressor (DiagnosticManager &mgr)
~DiagnosticSuppressor ()
Detailed Description
RAII helper for suppressing diagnostics in a scope.
Definition at line 266 of file DiagnosticManager.hpp.
Constructor & Destructor Documentation
DiagnosticSuppressor()
ml::DiagnosticSuppressor::DiagnosticSuppressor (DiagnosticManager & mgr) inline explicit
Definition at line 268 of file DiagnosticManager.hpp.
References ml::DiagnosticManager::setSuppressNotes(), and ml::DiagnosticManager::setSuppressWarnings().
~DiagnosticSuppressor()
ml::DiagnosticSuppressor::~DiagnosticSuppressor () inline
Definition at line 275 of file DiagnosticManager.hpp.
References ml::DiagnosticManager::setSuppressNotes(), and ml::DiagnosticManager::setSuppressWarnings().
The documentation for this class was generated from the following file:
include/ml/Managers/DiagnosticManager.hpp