my-lang: ml::StringInterner Class Reference
ml::StringInterner Class Reference
#include <StringInterner.hpp>
Classes
class const_iterator
Iterator support for debugging/inspection.
Public Member Functions
StringInterner ()
StringInterner (ArenaAllocator &arena)
~StringInterner ()
StringInterner (const StringInterner &)=delete
StringInterner & operator= (const StringInterner &)=delete
StringInterner (StringInterner &&other) noexcept
StringInterner & operator= (StringInterner &&other) noexcept
InternedString intern (std::string_view str)
Intern a string from various sources.
InternedString intern (const std::string &str)
InternedString intern (const char *str)
InternedString intern (const char *str, size_t len)
InternedString lookup (std::string_view str) const
bool contains (std::string_view str) const
Check if a string is already interned.
StringInternerStats getStats () const
Get statistics about the interner.
void clear ()
Clear all interned strings (invalidates all InternedString objects)
size_t size () const
Get the number of unique strings.
bool empty () const
Check if the interner is empty.
void printStats (std::ostream &os) const
Print statistics to the given stream.
void reserve (size_t count)
Reserve space for approximately this many strings (optimization)
size_t getMemoryUsage () const
Get memory usage in bytes.
bool isUsingArena () const
Check if using arena allocation.
ArenaAllocator * getArena () const
Get the arena allocator (if any)
const_iterator begin () const
const_iterator end () const
Detailed Description
A high-performance string interner that stores unique strings and provides fast comparison via pointer equality. This is essential for compiler performance when dealing with identifiers, keywords, and string literals.
Key features:
Thread-safe operations
Fast O(1) equality comparison via pointer comparison
Memory-efficient storage with automatic deduplication
Support for string_view to avoid unnecessary allocations
Statistics and debugging support
Definition at line 145 of file StringInterner.hpp.
Constructor & Destructor Documentation
StringInterner() [1/4]
ml::StringInterner::StringInterner ()
Definition at line 123 of file StringInterner.cpp.
StringInterner() [2/4]
ml::StringInterner::StringInterner (ArenaAllocator & arena) explicit
Create a StringInterner that uses an external arena allocator for improved memory locality and reduced heap fragmentation
Definition at line 129 of file StringInterner.cpp.
~StringInterner()
ml::StringInterner::~StringInterner () default
StringInterner() [3/4]
ml::StringInterner::StringInterner (const StringInterner &) delete
StringInterner() [4/4]
ml::StringInterner::StringInterner (StringInterner && other) noexcept
Definition at line 137 of file StringInterner.cpp.
Member Function Documentation
begin()
StringInterner::const_iterator ml::StringInterner::begin () const
Definition at line 339 of file StringInterner.cpp.
clear()
void ml::StringInterner::clear ()
Clear all interned strings (invalidates all InternedString objects)
Definition at line 245 of file StringInterner.cpp.
contains()
bool ml::StringInterner::contains (std::string_view str) const
Check if a string is already interned.
Definition at line 235 of file StringInterner.cpp.
empty()
bool ml::StringInterner::empty () const
Check if the interner is empty.
Definition at line 260 of file StringInterner.cpp.
end()
StringInterner::const_iterator ml::StringInterner::end () const
Definition at line 344 of file StringInterner.cpp.
getArena()
ArenaAllocator * ml::StringInterner::getArena () const inline
Get the arena allocator (if any)
Definition at line 205 of file StringInterner.hpp.
getMemoryUsage()
size_t ml::StringInterner::getMemoryUsage () const
Get memory usage in bytes.
Definition at line 291 of file StringInterner.cpp.
References ml::StringInternerStats::memoryUsedCount.
getStats()
StringInternerStats ml::StringInterner::getStats () const
Get statistics about the interner.
Definition at line 240 of file StringInterner.cpp.
Referenced by printStats().
intern() [1/4]
InternedString ml::StringInterner::intern (const char * str) inline
Definition at line 166 of file StringInterner.hpp.
References intern().
intern() [2/4]
InternedString ml::StringInterner::intern (const char * str, size_t len) inline
Definition at line 169 of file StringInterner.hpp.
References intern().
intern() [3/4]
InternedString ml::StringInterner::intern (const std::string & str) inline
Definition at line 163 of file StringInterner.hpp.
References intern().
intern() [4/4]
InternedString ml::StringInterner::intern (std::string_view str)
Intern a string from various sources.
Definition at line 158 of file StringInterner.cpp.
References ml::StringInternerStats::averageLength, ml::StringInternerStats::collisionCount, ml::StringInternerStats::internCount, ml::StringInternerStats::lookupCount, ml::StringInternerStats::memoryUsedCount, and ml::StringInternerStats::uniqueStringCount.
Referenced by ml::FileManager::fileExists(), ml::FileManager::getFileModTime(), ml::FileManager::getFileSize(), ml::FileManager::getFileWithError(), intern(), intern(), intern(), and ml::FileManager::removeFromCache().
isUsingArena()
bool ml::StringInterner::isUsingArena () const inline
Check if using arena allocation.
Definition at line 202 of file StringInterner.hpp.
lookup()
InternedString ml::StringInterner::lookup (std::string_view str) const
Lookup a string without interning (returns invalid InternedString if not found)
Definition at line 224 of file StringInterner.cpp.
operator=() [1/2]
StringInterner & ml::StringInterner::operator= (const StringInterner &) delete
operator=() [2/2]
StringInterner & ml::StringInterner::operator= (StringInterner && other) noexcept
Definition at line 143 of file StringInterner.cpp.
printStats()
void ml::StringInterner::printStats (std::ostream & os) const
Print statistics to the given stream.
Definition at line 265 of file StringInterner.cpp.
References ml::StringInternerStats::averageLength, ml::StringInternerStats::collisionCount, getStats(), ml::StringInternerStats::internCount, ml::StringInternerStats::lookupCount, ml::StringInternerStats::memoryUsedCount, and ml::StringInternerStats::uniqueStringCount.
Referenced by main().
reserve()
void ml::StringInterner::reserve (size_t count)
Reserve space for approximately this many strings (optimization)
Definition at line 284 of file StringInterner.cpp.
size()
size_t ml::StringInterner::size () const
Get the number of unique strings.
Definition at line 255 of file StringInterner.cpp.
The documentation for this class was generated from the following files:
include/ml/Basic/StringInterner.hpp
src/Basic/StringInterner.cpp