my-lang: ml::TokenInfo Class Reference
ml::TokenInfo Class Reference
Token information and utilities.
#include <Token.hpp>
Static Public Member Functions
static const char * getTokenSpelling (TokenKind kind)
Get the spelling of a token kind.
static const char * getTokenName (TokenKind kind)
Get the name of a token kind (for debugging)
static bool isKeyword (TokenKind kind)
Check if a token kind is a keyword.
static TokenKind getKeywordKind (std::string_view identifier)
Get keyword token kind from identifier text.
static bool isLiteral (TokenKind kind)
Check if a token kind is a literal.
static bool isOperator (TokenKind kind)
Check if a token kind is an operator.
static bool isPunctuation (TokenKind kind)
Check if a token kind is punctuation.
static int getOperatorPrecedence (TokenKind kind)
Get operator precedence (0 = not an operator)
static bool isLeftAssociative (TokenKind kind)
Check if operator is left associative.
static bool isRightAssociative (TokenKind kind)
Check if operator is right associative.
Detailed Description
Token information and utilities.
Definition at line 248 of file Token.hpp.
Member Function Documentation
getKeywordKind()
TokenKind ml::TokenInfo::getKeywordKind (std::string_view identifier) static
Get keyword token kind from identifier text.
Definition at line 355 of file Token.cpp.
References ml::Identifier, and ml::KEYWORD_LOOKUP_TABLE.
getOperatorPrecedence()
int ml::TokenInfo::getOperatorPrecedence (TokenKind kind) static
Get operator precedence (0 = not an operator)
Definition at line 381 of file Token.cpp.
References ml::createOperatorPrecedenceTable().
Referenced by isLeftAssociative().
getTokenName()
const char * ml::TokenInfo::getTokenName (TokenKind kind) static
Get the name of a token kind (for debugging)
Definition at line 343 of file Token.cpp.
References ml::Count, and ml::TokenNames.
Referenced by ml::operator<<(), and ml::operator<<().
getTokenSpelling()
const char * ml::TokenInfo::getTokenSpelling (TokenKind kind) static
Get the spelling of a token kind.
Definition at line 335 of file Token.cpp.
References ml::Count, and ml::TokenSpellings.
isKeyword()
bool ml::TokenInfo::isKeyword (TokenKind kind) static
Check if a token kind is a keyword.
Definition at line 351 of file Token.cpp.
References ml::Auto, and ml::While.
isLeftAssociative()
bool ml::TokenInfo::isLeftAssociative (TokenKind kind) static
Check if operator is left associative.
Definition at line 390 of file Token.cpp.
References ml::Equal, getOperatorPrecedence(), ml::MinusEqual, ml::PercentEqual, ml::PlusEqual, ml::SlashEqual, and ml::StarEqual.
isLiteral()
bool ml::TokenInfo::isLiteral (TokenKind kind) static
Check if a token kind is a literal.
Definition at line 369 of file Token.cpp.
References ml::Boolean, and ml::Integer.
isOperator()
bool ml::TokenInfo::isOperator (TokenKind kind) static
Check if a token kind is an operator.
Definition at line 373 of file Token.cpp.
References ml::MinusMinus, and ml::Plus.
isPunctuation()
bool ml::TokenInfo::isPunctuation (TokenKind kind) static
Check if a token kind is punctuation.
Definition at line 377 of file Token.cpp.
References ml::Hash, and ml::LeftParen.
isRightAssociative()
bool ml::TokenInfo::isRightAssociative (TokenKind kind) static
Check if operator is right associative.
Definition at line 398 of file Token.cpp.
References ml::Equal, ml::MinusEqual, ml::PercentEqual, ml::PlusEqual, ml::SlashEqual, and ml::StarEqual.
The documentation for this class was generated from the following files:
include/ml/Parse/Token.hpp
src/Parse/Token.cpp