my-lang: ml::SourceRange Class Reference
ml::SourceRange Class Reference
A range between two source locations.
#include <SourceLocation.hpp>
Public Member Functions
SourceRange ()=default
SourceRange (SourceLocation loc)
SourceRange (SourceLocation begin, SourceLocation end)
SourceLocation getBegin () const
Get the beginning location of the range.
SourceLocation getEnd () const
Get the ending location of the range.
void setBegin (SourceLocation loc)
Set the beginning location of the range.
void setEnd (SourceLocation loc)
Set the ending location of the range.
bool isValid () const
Check if the source range is valid.
bool isInvalid () const
Check if the source range is invalid.
bool operator== (const SourceRange &RHS) const
bool operator!= (const SourceRange &RHS) const
Detailed Description
A range between two source locations.
Represents a range in source code defined by a starting and ending location.
See also
SourceLocation for individual location representation.
Definition at line 152 of file SourceLocation.hpp.
Constructor & Destructor Documentation
SourceRange() [1/3]
ml::SourceRange::SourceRange () default
SourceRange() [2/3]
ml::SourceRange::SourceRange (SourceLocation loc) inline
Definition at line 155 of file SourceLocation.hpp.
SourceRange() [3/3]
ml::SourceRange::SourceRange (SourceLocation begin, SourceLocation end) inline
Definition at line 156 of file SourceLocation.hpp.
Member Function Documentation
getBegin()
SourceLocation ml::SourceRange::getBegin () const inline
Get the beginning location of the range.
Returns
The starting SourceLocation.
Definition at line 163 of file SourceLocation.hpp.
Referenced by ml::TokenManager::findTokenAtLocation(), ml::TokenManager::findTokensInRange(), and ml::SourceManager::getSourceText().
getEnd()
SourceLocation ml::SourceRange::getEnd () const inline
Get the ending location of the range.
Returns
The ending SourceLocation.
Definition at line 169 of file SourceLocation.hpp.
Referenced by ml::TokenManager::findTokenAtLocation(), ml::TokenManager::findTokensInRange(), and ml::SourceManager::getSourceText().
isInvalid()
bool ml::SourceRange::isInvalid () const inline
Check if the source range is invalid.
Returns
True if either begin or end locations are invalid.
See also
isValid()
Definition at line 195 of file SourceLocation.hpp.
References isValid().
isValid()
bool ml::SourceRange::isValid () const inline
Check if the source range is valid.
Returns
True if both begin and end locations are valid.
See also
isInvalid()
Definition at line 188 of file SourceLocation.hpp.
References ml::SourceLocation::isValid().
Referenced by isInvalid().
operator!=()
bool ml::SourceRange::operator!= (const SourceRange & RHS) const inline
Definition at line 200 of file SourceLocation.hpp.
operator==()
bool ml::SourceRange::operator== (const SourceRange & RHS) const inline
Definition at line 197 of file SourceLocation.hpp.
setBegin()
void ml::SourceRange::setBegin (SourceLocation loc) inline
Set the beginning location of the range.
Parameters
loc The new starting SourceLocation.
Definition at line 175 of file SourceLocation.hpp.
setEnd()
void ml::SourceRange::setEnd (SourceLocation loc) inline
Set the ending location of the range.
Parameters
loc The new ending SourceLocation.
Definition at line 181 of file SourceLocation.hpp.
The documentation for this class was generated from the following file:
include/ml/Basic/SourceLocation.hpp