my-lang: ml::DiagnosticManager Class Reference
ml::DiagnosticManager Class Reference
Main diagnostic manager class.
#include <DiagnosticManager.hpp>
Public Member Functions
DiagnosticManager (StringInterner &interner)
~DiagnosticManager ()
DiagnosticManager (const DiagnosticManager &)=delete
DiagnosticManager & operator= (const DiagnosticManager &)=delete
DiagnosticManager (DiagnosticManager &&) noexcept
DiagnosticManager & operator= (DiagnosticManager &&) noexcept
void setSourceManager (const SourceManager *srcMgr)
Set the source manager for location information.
void addConsumer (std::unique_ptr< DiagnosticConsumer > consumer)
Add a diagnostic consumer.
void clearConsumers ()
Remove all consumers.
void report (const Diagnostic &diag)
Report a diagnostic.
void report (DiagnosticID id, SourceLocation loc=SourceLocation())
Convenience methods for creating and reporting diagnostics.
void report (DiagnosticID id, SourceLocation loc, std::string_view arg1)
void report (DiagnosticID id, SourceLocation loc, std::string_view arg1, std::string_view arg2)
void setSuppressWarnings (bool suppress)
Diagnostic level filtering.
void setSuppressNotes (bool suppress)
void setWarningsAsErrors (bool enable)
void setMaxErrors (size_t max)
bool getSuppressWarnings () const
bool getSuppressNotes () const
bool getWarningsAsErrors () const
size_t getMaxErrors () const
DiagnosticStats getStats () const
Get diagnostic statistics.
bool hasErrors () const
Check if there have been errors.
bool hasWarnings () const
bool hasFatalErrors () const
void reset ()
Reset statistics.
bool shouldContinue () const
Check if we should continue compilation.
void printStats (std::ostream &os) const
Print statistics.
Static Public Member Functions
static const DiagnosticInfo & getDiagnosticInfo (DiagnosticID id)
Get diagnostic information by id.
Detailed Description
Main diagnostic manager class.
Definition at line 179 of file DiagnosticManager.hpp.
Constructor & Destructor Documentation
DiagnosticManager() [1/3]
ml::DiagnosticManager::DiagnosticManager (StringInterner & interner) explicit
Definition at line 22 of file DiagnosticManager.cpp.
~DiagnosticManager()
ml::DiagnosticManager::~DiagnosticManager () default
DiagnosticManager() [2/3]
ml::DiagnosticManager::DiagnosticManager (const DiagnosticManager &) delete
DiagnosticManager() [3/3]
ml::DiagnosticManager::DiagnosticManager (DiagnosticManager && other) noexcept
Definition at line 27 of file DiagnosticManager.cpp.
Member Function Documentation
addConsumer()
void ml::DiagnosticManager::addConsumer (std::unique_ptr< DiagnosticConsumer > consumer)
Add a diagnostic consumer.
Definition at line 35 of file DiagnosticManager.cpp.
Referenced by main().
clearConsumers()
void ml::DiagnosticManager::clearConsumers ()
Remove all consumers.
Definition at line 40 of file DiagnosticManager.cpp.
getDiagnosticInfo()
const DiagnosticInfo & ml::DiagnosticManager::getDiagnosticInfo (DiagnosticID id) static
Get diagnostic information by id.
Definition at line 118 of file DiagnosticManager.cpp.
References ml::Error, ml::NumDiagnostics, and ml::System.
Referenced by report().
getMaxErrors()
size_t ml::DiagnosticManager::getMaxErrors () const inline
Definition at line 217 of file DiagnosticManager.hpp.
getStats()
DiagnosticStats ml::DiagnosticManager::getStats () const
Get diagnostic statistics.
Definition at line 93 of file DiagnosticManager.cpp.
Referenced by printStats().
getSuppressNotes()
bool ml::DiagnosticManager::getSuppressNotes () const inline
Definition at line 215 of file DiagnosticManager.hpp.
getSuppressWarnings()
bool ml::DiagnosticManager::getSuppressWarnings () const inline
Definition at line 214 of file DiagnosticManager.hpp.
getWarningsAsErrors()
bool ml::DiagnosticManager::getWarningsAsErrors () const inline
Definition at line 216 of file DiagnosticManager.hpp.
hasErrors()
bool ml::DiagnosticManager::hasErrors () const
Check if there have been errors.
Definition at line 98 of file DiagnosticManager.cpp.
References ml::DiagnosticStats::hasErrors().
hasFatalErrors()
bool ml::DiagnosticManager::hasFatalErrors () const
Definition at line 108 of file DiagnosticManager.cpp.
References ml::DiagnosticStats::fatalCount.
hasWarnings()
bool ml::DiagnosticManager::hasWarnings () const
Definition at line 103 of file DiagnosticManager.cpp.
References ml::DiagnosticStats::hasWarnings().
operator=() [1/2]
DiagnosticManager & ml::DiagnosticManager::operator= (const DiagnosticManager &) delete
operator=() [2/2]
DiagnosticManager & ml::DiagnosticManager::operator= (DiagnosticManager &&) noexcept
printStats()
void ml::DiagnosticManager::printStats (std::ostream & os) const
Print statistics.
Definition at line 147 of file DiagnosticManager.cpp.
References ml::DiagnosticStats::diagnosticCount, ml::DiagnosticStats::errorCount, ml::DiagnosticStats::fatalCount, getStats(), ml::DiagnosticStats::noteCount, and ml::DiagnosticStats::warningCount.
Referenced by main().
report() [1/4]
void ml::DiagnosticManager::report (const Diagnostic & diag)
Report a diagnostic.
Definition at line 42 of file DiagnosticManager.cpp.
References ml::Error, ml::DiagnosticStats::errorCount, getDiagnosticInfo(), ml::Diagnostic::getID(), ml::DiagnosticInfo::Level, and ml::Warning.
Referenced by report(), report(), and report().
report() [2/4]
void ml::DiagnosticManager::report (DiagnosticID id, SourceLocation loc, std::string_view arg1)
Definition at line 79 of file DiagnosticManager.cpp.
References ml::Diagnostic::addArg(), and report().
report() [3/4]
void ml::DiagnosticManager::report (DiagnosticID id, SourceLocation loc, std::string_view arg1, std::string_view arg2)
Definition at line 86 of file DiagnosticManager.cpp.
References ml::Diagnostic::addArg(), and report().
report() [4/4]
void ml::DiagnosticManager::report (DiagnosticID id, SourceLocation loc = SourceLocation())
Convenience methods for creating and reporting diagnostics.
Definition at line 74 of file DiagnosticManager.cpp.
References report().
reset()
void ml::DiagnosticManager::reset ()
Reset statistics.
Definition at line 113 of file DiagnosticManager.cpp.
setMaxErrors()
void ml::DiagnosticManager::setMaxErrors (size_t max) inline
Definition at line 212 of file DiagnosticManager.hpp.
setSourceManager()
void ml::DiagnosticManager::setSourceManager (const SourceManager * srcMgr) inline
Set the source manager for location information.
Definition at line 191 of file DiagnosticManager.hpp.
Referenced by main().
setSuppressNotes()
void ml::DiagnosticManager::setSuppressNotes (bool suppress) inline
Definition at line 210 of file DiagnosticManager.hpp.
Referenced by ml::DiagnosticSuppressor::DiagnosticSuppressor(), and ml::DiagnosticSuppressor::~DiagnosticSuppressor().
setSuppressWarnings()
void ml::DiagnosticManager::setSuppressWarnings (bool suppress) inline
Diagnostic level filtering.
Definition at line 209 of file DiagnosticManager.hpp.
Referenced by ml::DiagnosticSuppressor::DiagnosticSuppressor(), and ml::DiagnosticSuppressor::~DiagnosticSuppressor().
setWarningsAsErrors()
void ml::DiagnosticManager::setWarningsAsErrors (bool enable) inline
Definition at line 211 of file DiagnosticManager.hpp.
shouldContinue()
bool ml::DiagnosticManager::shouldContinue () const
Check if we should continue compilation.
Definition at line 131 of file DiagnosticManager.cpp.
References ml::DiagnosticStats::errorCount, and ml::DiagnosticStats::fatalCount.
The documentation for this class was generated from the following files:
include/ml/Managers/DiagnosticManager.hpp
src/Managers/DiagnosticManager.cpp