my-lang: ml::ArenaAllocator Class Reference
ml::ArenaAllocator Class Reference
An allocator using arena allocation strategy.
#include "ml/Basic/ArenaAllocator.hpp"
Public Member Functions
ArenaAllocator (size_t chunkSize=kDefaultChunkSize)
~ArenaAllocator ()
ArenaAllocator (const ArenaAllocator &)=delete
ArenaAllocator & operator= (const ArenaAllocator &)=delete
ArenaAllocator (ArenaAllocator &&) noexcept
ArenaAllocator & operator= (ArenaAllocator &&) noexcept
void * allocate (size_t size)
Allocates memory with default alignment.
void * allocate (size_t size, size_t alignment)
Allocates memory with specified alignment.
template<typename T , typename... Args>
T * allocate (Args &&...args)
Allocates and constructs an object of type T.
template<typename T >
T * allocateArray (size_t count)
Allocates an array of objects.
char * allocateString (const char *str, size_t length)
Allocates a string in the arena.
char * allocateString (const char *str)
void reset ()
Resets the arena, freeing all allocated memory.
void clear ()
Clears the arena, resetting all chunks.
ArenaStats getStats () const
Gets the current allocation statistics.
bool contains (const void *ptr) const
Checks if a pointer belongs to this arena.
size_t getTotalAllocated () const
Get total allocated memory.
size_t getTotalUsed () const
Get total used memory.
void printStats (std::ostream &OS) const
Print statistics.
void setChunkSize (size_t size)
Sets the chunk size for future allocations.
size_t getChunkSize () const
Gets the current chunk size.
Static Public Attributes
static constexpr size_t kDefaultChunkSize = 1024 * 1024
The default chunk size for allocations. 1MB.
static constexpr size_t kDefaultAlignment = alignof(std::max_align_t)
The default alignment for allocations. 16 bytes.
static constexpr size_t kMaxAllocationSize = 512 * 1024
The maximum allocation size supported by the arena. 512KB.
Detailed Description
An allocator using arena allocation strategy.
Mnages memory in large chunks to provide fast allocation and deallocation of small to medium-sized objects, minimizing fragmentation and overhead. It is particularly well-suited for compiler use cases where many temporary objects are created.
See also
ArenaStats for tracking allocation statistics.
ArenaChunk for individual memory chunk management.
Definition at line 192 of file ArenaAllocator.hpp.
Constructor & Destructor Documentation
ArenaAllocator() [1/3]
ml::ArenaAllocator::ArenaAllocator (size_t chunkSize = kDefaultChunkSize) explicit
~ArenaAllocator()
ml::ArenaAllocator::~ArenaAllocator ()
ArenaAllocator() [2/3]
ml::ArenaAllocator::ArenaAllocator (const ArenaAllocator &) delete
ArenaAllocator() [3/3]
ml::ArenaAllocator::ArenaAllocator (ArenaAllocator &&) noexcept
Member Function Documentation
allocate() [1/3]
template<typename T , typename... Args> T * ml::ArenaAllocator::allocate (Args &&... args) inline
Allocates and constructs an object of type T.
Template Parameters
T The type of object to allocate
Args The constructor argument types
Parameters
args The constructor arguments
Returns
A pointer to the constructed object.
Definition at line 239 of file ArenaAllocator.hpp.
References allocate(), and kMaxAllocationSize.
allocate() [2/3]
void * ml::ArenaAllocator::allocate (size_t size) inline
Allocates memory with default alignment.
Parameters
size The size of memory to allocate
Returns
A pointer to the allocated memory or nullptr if allocation fails.
Definition at line 222 of file ArenaAllocator.hpp.
References allocate(), and kDefaultAlignment.
Referenced by allocate(), allocate(), ml::ArenaSTLAllocator< T >::allocate(), and allocateArray().
allocate() [3/3]
void * ml::ArenaAllocator::allocate (size_t size, size_t alignment)
Allocates memory with specified alignment.
Parameters
size The size of memory to allocate
alignment The required alignment
Returns
A pointer to the allocated memory or nullptr if allocation fails.
allocateArray()
template<typename T > T * ml::ArenaAllocator::allocateArray (size_t count) inline
Allocates an array of objects.
Template Parameters
T The type of objects to allocate
Parameters
count The number of objects to allocate
Returns
A pointer to the allocated array or nullptr if allocation fails.
Definition at line 257 of file ArenaAllocator.hpp.
References allocate(), and kMaxAllocationSize.
allocateString() [1/2]
char * ml::ArenaAllocator::allocateString (const char * str) inline
Definition at line 281 of file ArenaAllocator.hpp.
References allocateString().
allocateString() [2/2]
char * ml::ArenaAllocator::allocateString (const char * str, size_t length)
Allocates a string in the arena.
Parameters
str The string data
length The length of the string
Returns
A pointer to the allocated string.
Referenced by allocateString().
clear()
void ml::ArenaAllocator::clear ()
Clears the arena, resetting all chunks.
This does not free memory but makes it available for reuse.
See also
reset() for full deallocation.
contains()
bool ml::ArenaAllocator::contains (const void * ptr) const
Checks if a pointer belongs to this arena.
Parameters
ptr The pointer to check
Returns
True if the pointer was allocated by this arena
getChunkSize()
size_t ml::ArenaAllocator::getChunkSize () const inline
Gets the current chunk size.
Returns
The chunk size in bytes
Definition at line 339 of file ArenaAllocator.hpp.
getStats()
ArenaStats ml::ArenaAllocator::getStats () const
Gets the current allocation statistics.
Returns
The current ArenaStats.
Referenced by ml::ArenaScope::ArenaScope().
getTotalAllocated()
size_t ml::ArenaAllocator::getTotalAllocated () const
Get total allocated memory.
Returns
Total allocated memory in bytes
getTotalUsed()
size_t ml::ArenaAllocator::getTotalUsed () const
Get total used memory.
Returns
Total used memory in bytes
operator=() [1/2]
ArenaAllocator & ml::ArenaAllocator::operator= (ArenaAllocator &&) noexcept
operator=() [2/2]
ArenaAllocator & ml::ArenaAllocator::operator= (const ArenaAllocator &) delete
printStats()
void ml::ArenaAllocator::printStats (std::ostream & OS) const
Print statistics.
Parameters
OS The output stream to print to
reset()
void ml::ArenaAllocator::reset ()
Resets the arena, freeing all allocated memory.
This invalidates all previously allocated memory.
setChunkSize()
void ml::ArenaAllocator::setChunkSize (size_t size) inline
Sets the chunk size for future allocations.
Parameters
size The new chunk size in bytes
Definition at line 333 of file ArenaAllocator.hpp.
Member Data Documentation
kDefaultAlignment
constexpr size_t ml::ArenaAllocator::kDefaultAlignment = alignof(std::max_align_t) static constexpr
The default alignment for allocations. 16 bytes.
Definition at line 202 of file ArenaAllocator.hpp.
Referenced by allocate().
kDefaultChunkSize
constexpr size_t ml::ArenaAllocator::kDefaultChunkSize = 1024 * 1024 static constexpr
The default chunk size for allocations. 1MB.
Definition at line 197 of file ArenaAllocator.hpp.
kMaxAllocationSize
constexpr size_t ml::ArenaAllocator::kMaxAllocationSize = 512 * 1024 static constexpr
The maximum allocation size supported by the arena. 512KB.
Definition at line 207 of file ArenaAllocator.hpp.
Referenced by allocate(), ml::ArenaSTLAllocator< T >::allocate(), and allocateArray().
The documentation for this class was generated from the following file:
include/ml/Basic/ArenaAllocator.hpp