my-lang: ml::JSONDiagnosticConsumer Class Reference
ml::JSONDiagnosticConsumer Class Reference
Built-in JSON diagnostic consumer.
#include <DiagnosticManager.hpp>
Public Member Functions
JSONDiagnosticConsumer (std::ostream &os)
void beginSourceFile () override
Called before processing a batch of diagnostics.
void handleDiagnostic (const Diagnostic &diag, const DiagnosticInfo &info, const SourceManager *srcMgr) override
Called to handle a single diagnostic.
void endSourceFile () override
Called after processing a batch of diagnostics.
Public Member Functions inherited from ml::DiagnosticConsumer
virtual ~DiagnosticConsumer ()=default
virtual void finish ()
Called when diagnostics are finished.
Detailed Description
Built-in JSON diagnostic consumer.
Definition at line 164 of file DiagnosticManager.hpp.
Constructor & Destructor Documentation
JSONDiagnosticConsumer()
ml::JSONDiagnosticConsumer::JSONDiagnosticConsumer (std::ostream & os) inline explicit
Definition at line 166 of file DiagnosticManager.hpp.
Member Function Documentation
beginSourceFile()
void ml::JSONDiagnosticConsumer::beginSourceFile () override virtual
Called before processing a batch of diagnostics.
Reimplemented from ml::DiagnosticConsumer.
Definition at line 340 of file DiagnosticManager.cpp.
endSourceFile()
void ml::JSONDiagnosticConsumer::endSourceFile () override virtual
Called after processing a batch of diagnostics.
Reimplemented from ml::DiagnosticConsumer.
Definition at line 409 of file DiagnosticManager.cpp.
handleDiagnostic()
void ml::JSONDiagnosticConsumer::handleDiagnostic (const Diagnostic & diag, const DiagnosticInfo & info, const SourceManager * srcMgr) override virtual
Called to handle a single diagnostic.
Implements ml::DiagnosticConsumer.
Definition at line 345 of file DiagnosticManager.cpp.
References ml::DiagnosticInfo::DetailedMessage, ml::Error, ml::Fatal, ml::Diagnostic::getArguments(), ml::FullSourceLoc::getFilename(), ml::SourceManager::getFullLoc(), ml::Diagnostic::getID(), ml::Diagnostic::getLocation(), ml::SourceLocation::isValid(), ml::DiagnosticInfo::Level, ml::Note, and ml::Warning.
The documentation for this class was generated from the following files:
include/ml/Managers/DiagnosticManager.hpp
src/Managers/DiagnosticManager.cpp