my-lang: ml::Token Class Reference
ml::Token Class Reference
A single token with location and metadata.
#include <Token.hpp>
Public Member Functions
Token ()
Token (TokenKind kind, SourceLocation loc, uint32_t length)
Token (TokenKind kind, SourceLocation loc, uint32_t length, InternedString text)
TokenKind getKind () const
SourceLocation getLocation () const
uint32_t getLength () const
TokenFlags getFlags () const
InternedString getText () const
void setKind (TokenKind kind)
void setLocation (SourceLocation loc)
void setLength (uint32_t length)
void setFlags (TokenFlags flags)
void setText (InternedString text)
bool hasFlag (TokenFlags flag) const
void addFlag (TokenFlags flag)
void removeFlag (TokenFlags flag)
bool isAtStartOfLine () const
bool hasLeadingSpace () const
bool isKeyword () const
bool isLiteral () const
bool isOperator () const
bool isPunctuation () const
bool isIdentifierOrKeyword () const
SourceRange getSourceRange () const
bool operator== (const Token &other) const
bool operator!= (const Token &other) const
bool is (TokenKind kind) const
template<typename... Kinds>
bool isOneOf (TokenKind kind1, Kinds... kinds) const
bool isOneOf () const
bool isNot (TokenKind kind) const
template<typename... Kinds>
bool isNotOneOf (Kinds... kinds) const
Detailed Description
A single token with location and metadata.
Definition at line 149 of file Token.hpp.
Constructor & Destructor Documentation
Token() [1/3]
ml::Token::Token () inline
Definition at line 151 of file Token.hpp.
Token() [2/3]
ml::Token::Token (TokenKind kind, SourceLocation loc, uint32_t length) inline
Definition at line 153 of file Token.hpp.
Token() [3/3]
ml::Token::Token (TokenKind kind, SourceLocation loc, uint32_t length, InternedString text) inline
Definition at line 156 of file Token.hpp.
Member Function Documentation
addFlag()
void ml::Token::addFlag (TokenFlags flag) inline
Definition at line 180 of file Token.hpp.
Referenced by ml::Lexer::nextToken().
getFlags()
TokenFlags ml::Token::getFlags () const inline
Definition at line 165 of file Token.hpp.
getKind()
TokenKind ml::Token::getKind () const inline
Definition at line 162 of file Token.hpp.
Referenced by ml::operator<<(), ml::tokenizeFile(), ml::BatchTokenizer::tokenizeStreaming(), and ml::tokenizeString().
getLength()
uint32_t ml::Token::getLength () const inline
Definition at line 164 of file Token.hpp.
getLocation()
SourceLocation ml::Token::getLocation () const inline
Definition at line 163 of file Token.hpp.
getSourceRange()
SourceRange ml::Token::getSourceRange () const inline
Definition at line 206 of file Token.hpp.
References ml::SourceLocation::getFromRawEncoding(), and ml::SourceLocation::getRawEncoding().
Referenced by ml::TokenManager::findTokenAtLocation().
getText()
InternedString ml::Token::getText () const inline
Definition at line 166 of file Token.hpp.
Referenced by ml::operator<<().
hasFlag()
bool ml::Token::hasFlag (TokenFlags flag) const inline
Definition at line 176 of file Token.hpp.
References ml::None.
Referenced by hasLeadingSpace(), isAtStartOfLine(), and isKeyword().
hasLeadingSpace()
bool ml::Token::hasLeadingSpace () const inline
Definition at line 189 of file Token.hpp.
References hasFlag(), and ml::HasLeadingSpace.
is()
bool ml::Token::is (TokenKind kind) const inline
Definition at line 223 of file Token.hpp.
Referenced by isOneOf().
isAtStartOfLine()
bool ml::Token::isAtStartOfLine () const inline
Definition at line 188 of file Token.hpp.
References ml::AtStartOfLine, and hasFlag().
isIdentifierOrKeyword()
bool ml::Token::isIdentifierOrKeyword () const inline
Definition at line 200 of file Token.hpp.
References ml::Auto, ml::Identifier, and ml::While.
isKeyword()
bool ml::Token::isKeyword () const inline
Definition at line 190 of file Token.hpp.
References hasFlag(), and ml::IsKeyword.
isLiteral()
bool ml::Token::isLiteral () const inline
Definition at line 191 of file Token.hpp.
References ml::Boolean, and ml::Integer.
isNot()
bool ml::Token::isNot (TokenKind kind) const inline
Definition at line 233 of file Token.hpp.
isNotOneOf()
template<typename... Kinds> bool ml::Token::isNotOneOf (Kinds... kinds) const inline
Definition at line 235 of file Token.hpp.
References isOneOf().
isOneOf() [1/2]
bool ml::Token::isOneOf () const inline
Definition at line 230 of file Token.hpp.
Referenced by isNotOneOf(), and isOneOf().
isOneOf() [2/2]
template<typename... Kinds> bool ml::Token::isOneOf (TokenKind kind1, Kinds... kinds) const inline
Definition at line 226 of file Token.hpp.
References is(), and isOneOf().
isOperator()
bool ml::Token::isOperator () const inline
Definition at line 194 of file Token.hpp.
References ml::MinusMinus, and ml::Plus.
isPunctuation()
bool ml::Token::isPunctuation () const inline
Definition at line 197 of file Token.hpp.
References ml::Hash, and ml::LeftParen.
operator!=()
bool ml::Token::operator!= (const Token & other) const inline
Definition at line 220 of file Token.hpp.
operator==()
bool ml::Token::operator== (const Token & other) const inline
Definition at line 215 of file Token.hpp.
removeFlag()
void ml::Token::removeFlag (TokenFlags flag) inline
Definition at line 182 of file Token.hpp.
setFlags()
void ml::Token::setFlags (TokenFlags flags) inline
Definition at line 172 of file Token.hpp.
setKind()
void ml::Token::setKind (TokenKind kind) inline
Definition at line 169 of file Token.hpp.
setLength()
void ml::Token::setLength (uint32_t length) inline
Definition at line 171 of file Token.hpp.
setLocation()
void ml::Token::setLocation (SourceLocation loc) inline
Definition at line 170 of file Token.hpp.
setText()
void ml::Token::setText (InternedString text) inline
Definition at line 173 of file Token.hpp.
The documentation for this class was generated from the following file:
include/ml/Parse/Token.hpp