my-lang: ml::SourceLocation Class Reference
ml::SourceLocation Class Reference
A specific location in source code.
#include <SourceLocation.hpp>
Public Member Functions
SourceLocation ()
bool isValid () const
Check if the SourceLocation is valid.
bool isInvalid () const
Check if the SourceLocation is invalid.
bool operator== (const SourceLocation &RHS) const
bool operator!= (const SourceLocation &RHS) const
bool operator< (const SourceLocation &RHS) const
uint32_t getHashValue () const
Get the hash value of this SourceLocation.
uint32_t getRawEncoding () const
Get the raw encoding of this SourceLocation.
void print (std::ostream &os, const SourceManager &SM) const
Print the source location using the provided SourceManager.
std::string printToString (const SourceManager &SM) const
Get a string representation of the source location.
Static Public Member Functions
static SourceLocation getInvalidLoc ()
Get an invalid SourceLocation.
static SourceLocation getFromRawEncoding (uint32_t encoding)
Create a SourceLocation from a raw encoding.
Friends
class SourceManager
Detailed Description
A specific location in source code.
Encapsulates a specific location within a source file, providing an efficient 32-bit representation that can represent locations in files up to 4GB in size.
See also
SourceManager for usage cases.
Definition at line 68 of file SourceLocation.hpp.
Constructor & Destructor Documentation
SourceLocation()
ml::SourceLocation::SourceLocation () inline
Definition at line 70 of file SourceLocation.hpp.
Referenced by getInvalidLoc().
Member Function Documentation
getFromRawEncoding()
static SourceLocation ml::SourceLocation::getFromRawEncoding (uint32_t encoding) inline static
Create a SourceLocation from a raw encoding.
Parameters
encoding The raw encoding as a uint32_t.
Returns
The corresponding SourceLocation.
See also
getRawEncoding() for the inverse operation.
Definition at line 115 of file SourceLocation.hpp.
Referenced by ml::Token::getSourceRange().
getHashValue()
uint32_t ml::SourceLocation::getHashValue () const inline
Get the hash value of this SourceLocation.
Returns
The hash value as a uint32_t.
Definition at line 100 of file SourceLocation.hpp.
getInvalidLoc()
static SourceLocation ml::SourceLocation::getInvalidLoc () inline static
Get an invalid SourceLocation.
Returns
An invalid SourceLocation instance. SourceLocation()
Definition at line 90 of file SourceLocation.hpp.
References SourceLocation().
Referenced by ml::SourceManager::advanceSourceLocation(), ml::SourceManager::getLocForEndOfFile(), ml::SourceManager::getLocForFileOffset(), ml::SourceManager::getLocForStartOfFile(), and ml::LocationCache::invalidate().
getRawEncoding()
uint32_t ml::SourceLocation::getRawEncoding () const inline
Get the raw encoding of this SourceLocation.
Returns
The raw encoding as a uint32_t.
See also
getFromRawEncoding(uint32_t) for the inverse operation.
Definition at line 107 of file SourceLocation.hpp.
Referenced by ml::SourceManager::advanceSourceLocation(), ml::TokenManager::findTokenAtLocation(), ml::TokenManager::findTokensInRange(), ml::SourceManager::getFileID(), ml::SourceManager::getFileOffset(), ml::Token::getSourceRange(), ml::SourceManager::isBeforeInSourceOrder(), and ml::operator<<().
isInvalid()
bool ml::SourceLocation::isInvalid () const inline
Check if the SourceLocation is invalid.
Returns
True if invalid, false otherwise.
See also
isValid()
Definition at line 84 of file SourceLocation.hpp.
Referenced by ml::SourceManager::advanceSourceLocation(), ml::SourceManager::getColumnNumber(), ml::SourceManager::getFileID(), ml::SourceManager::getLineNumber(), ml::SourceManager::getSourceLength(), ml::SourceManager::getSourceText(), ml::SourceManager::isBeforeInSourceOrder(), and print().
isValid()
bool ml::SourceLocation::isValid () const inline
Check if the SourceLocation is valid.
Returns
True if valid, false otherwise.
See also
isInvalid()
Definition at line 77 of file SourceLocation.hpp.
Referenced by ml::SourceManager::getColumnNumber(), ml::SourceManager::getFileID(), ml::SourceManager::getLineNumber(), ml::TextDiagnosticConsumer::handleDiagnostic(), ml::JSONDiagnosticConsumer::handleDiagnostic(), ml::SourceRange::isValid(), ml::FullSourceLoc::isValid(), and ml::SourceManager::isValidSourceLocation().
operator!=()
bool ml::SourceLocation::operator!= (const SourceLocation & RHS) const inline
Definition at line 93 of file SourceLocation.hpp.
operator<()
bool ml::SourceLocation::operator< (const SourceLocation & RHS) const inline
Definition at line 94 of file SourceLocation.hpp.
operator==()
bool ml::SourceLocation::operator== (const SourceLocation & RHS) const inline
Definition at line 92 of file SourceLocation.hpp.
print()
void ml::SourceLocation::print (std::ostream & os, const SourceManager & SM) const
Print the source location using the provided SourceManager.
Parameters
os The output stream to print to.
See also
printToString(const SourceManager &) const for string representation.
Definition at line 55 of file SourceManager.cpp.
References ml::SourceManager::getColumnNumber(), ml::SourceManager::getFilenameView(), ml::SourceManager::getLineNumber(), and isInvalid().
Referenced by printToString().
printToString()
std::string ml::SourceLocation::printToString (const SourceManager & SM) const
Get a string representation of the source location.
Parameters
SM The SourceManager to use for context.
Returns
A string representing the source location.
See also
print(std::ostream &, const SourceManager &) const for printing.
Definition at line 68 of file SourceManager.cpp.
References print().
Friends And Related Symbol Documentation
SourceManager
friend class SourceManager friend
Definition at line 137 of file SourceLocation.hpp.
The documentation for this class was generated from the following files:
include/ml/Basic/SourceLocation.hpp
src/Managers/SourceManager.cpp