my-lang: ml::Lexer Class Reference
ml::Lexer Class Reference
Main lexer class for tokenizing source code.
#include <Lexer.hpp>
Public Member Functions
Lexer (const SourceManager &srcMgr, FileID fileID, StringInterner &interner, DiagnosticManager &diagMgr, const LexerOptions &opts=LexerOptions{})
Lexer (std::string_view source, StringInterner &interner, DiagnosticManager &diagMgr, const LexerOptions &opts=LexerOptions{})
~Lexer ()
Lexer (const Lexer &)=delete
Lexer & operator= (const Lexer &)=delete
Lexer (Lexer &&) noexcept
Lexer & operator= (Lexer &&) noexcept
Token nextToken ()
Tokenize the next token.
const Token & peekToken ()
Peek at the next token without consuming it.
bool isAtEnd () const
Check if we've reached the end of the file.
SourceLocation getCurrentLocation () const
Get current position in the source.
uint32_t getCurrentLine () const
Get the current line number.
uint32_t getCurrentColumn () const
Get the current column number.
void skipToEndOfLine ()
Skip to the end of the current line.
void skipTrivial ()
Skip whitespace and comments.
void skipTrivialOptimized ()
Skip whitespace and comments (optimized version)
void reset ()
Reset to the beginning of the source.
void setPreprocessorCallback (PreprocessorCallback callback)
Set preprocessor directive callback.
LexerStats getStats () const
Get lexer statistics.
const LexerOptions & getOptions () const
Get lexer options.
std::string_view getSourceText () const
Get the source text.
FileID getFileID () const
Get the FileID (if lexing from SourceManager)
void printStats (std::ostream &os) const
Detailed Description
Main lexer class for tokenizing source code.
Definition at line 68 of file Lexer.hpp.
Constructor & Destructor Documentation
Lexer() [1/4]
ml::Lexer::Lexer (const SourceManager & srcMgr, FileID fileID, StringInterner & interner, DiagnosticManager & diagMgr, const LexerOptions & opts = LexerOptions{})
Definition at line 189 of file Lexer.cpp.
References ml::FileEntry::getBufferStart(), ml::SourceManager::getFileEntry(), and ml::FileEntry::getSize().
Lexer() [2/4]
ml::Lexer::Lexer (std::string_view source, StringInterner & interner, DiagnosticManager & diagMgr, const LexerOptions & opts = LexerOptions{})
Definition at line 207 of file Lexer.cpp.
~Lexer()
ml::Lexer::~Lexer () default
Lexer() [3/4]
ml::Lexer::Lexer (const Lexer &) delete
Lexer() [4/4]
ml::Lexer::Lexer (Lexer && other) noexcept
Definition at line 220 of file Lexer.cpp.
Member Function Documentation
getCurrentColumn()
uint32_t ml::Lexer::getCurrentColumn () const
Get the current column number.
Definition at line 408 of file Lexer.cpp.
getCurrentLine()
uint32_t ml::Lexer::getCurrentLine () const inline
Get the current line number.
Definition at line 97 of file Lexer.hpp.
getCurrentLocation()
SourceLocation ml::Lexer::getCurrentLocation () const
Get current position in the source.
Definition at line 404 of file Lexer.cpp.
getFileID()
FileID ml::Lexer::getFileID () const inline
Get the FileID (if lexing from SourceManager)
Definition at line 129 of file Lexer.hpp.
getOptions()
const LexerOptions & ml::Lexer::getOptions () const inline
Get lexer options.
Definition at line 123 of file Lexer.hpp.
getSourceText()
std::string_view ml::Lexer::getSourceText () const inline
Get the source text.
Definition at line 126 of file Lexer.hpp.
getStats()
LexerStats ml::Lexer::getStats () const
Get lexer statistics.
Definition at line 510 of file Lexer.cpp.
References ml::LexerStats::characterCount, and ml::LexerStats::lineCount.
Referenced by ml::BatchTokenizer::tokenizeStreaming().
isAtEnd()
bool ml::Lexer::isAtEnd () const
Check if we've reached the end of the file.
Definition at line 402 of file Lexer.cpp.
Referenced by main(), nextToken(), skipToEndOfLine(), and skipTrivial().
nextToken()
Token ml::Lexer::nextToken ()
Tokenize the next token.
Definition at line 232 of file Lexer.cpp.
References ml::Token::addFlag(), ml::AtStartOfLine, ml::LexerStats::characterCount, ml::LexerOptions::enableFastPath, ml::LexerOptions::enableLookupTables, ml::LexerOptions::enablePrefetching, ml::EndOfFile, ml::isAlphaFast(), isAtEnd(), ml::isDigitFast(), ml::isNewlineFast(), ml::isWhitespaceFast(), ml::LexerStats::lexingTimeMs, ml::LexerStats::lookupTableHits, ml::Newline, nextToken(), ml::LexerOptions::retainComments, ml::LexerOptions::retainWhitespace, skipTrivialOptimized(), ml::LexerStats::tokenCount, ml::LexerStats::updateAverages(), and ml::Whitespace.
Referenced by main(), nextToken(), peekToken(), ml::tokenizeFile(), ml::BatchTokenizer::tokenizeStreaming(), and ml::tokenizeString().
operator=() [1/2]
Lexer & ml::Lexer::operator= (const Lexer &) delete
operator=() [2/2]
Lexer & ml::Lexer::operator= (Lexer &&) noexcept
peekToken()
const Token & ml::Lexer::peekToken ()
Peek at the next token without consuming it.
Definition at line 394 of file Lexer.cpp.
References nextToken().
printStats()
void ml::Lexer::printStats (std::ostream & os) const
Definition at line 1323 of file Lexer.cpp.
References ml::LexerStats::branchMisses, ml::LexerStats::characterCount, ml::LexerStats::commentCount, ml::LexerStats::identifierCount, ml::LexerStats::keywordCount, ml::LexerStats::lexingTimeMs, ml::LexerStats::lineCount, ml::LexerStats::literalCount, ml::LexerStats::lookupTableHits, ml::LexerStats::simdOperations, and ml::LexerStats::tokenCount.
Referenced by main().
reset()
void ml::Lexer::reset ()
Reset to the beginning of the source.
Definition at line 501 of file Lexer.cpp.
setPreprocessorCallback()
void ml::Lexer::setPreprocessorCallback (PreprocessorCallback callback) inline
Set preprocessor directive callback.
Definition at line 115 of file Lexer.hpp.
skipToEndOfLine()
void ml::Lexer::skipToEndOfLine ()
Skip to the end of the current line.
Definition at line 412 of file Lexer.cpp.
References isAtEnd().
skipTrivial()
void ml::Lexer::skipTrivial ()
Skip whitespace and comments.
Definition at line 418 of file Lexer.cpp.
References isAtEnd().
skipTrivialOptimized()
void ml::Lexer::skipTrivialOptimized ()
Skip whitespace and comments (optimized version)
Definition at line 437 of file Lexer.cpp.
References ml::LexerStats::characterCount, ml::LexerOptions::enableLookupTables, ml::LexerOptions::enableSimdOptimizations, ml::isNewlineFast(), ml::isWhitespaceFast(), ml::LexerStats::simdOperations, and ml::skipWhitespaceSimdWithStats().
Referenced by nextToken().
The documentation for this class was generated from the following files:
include/ml/Parse/Lexer.hpp
src/Parse/Lexer.cpp