my-lang: ml::InternedString Class Reference
ml::InternedString Class Reference
An interned string handle.
#include "ml/Basic/StringInterner.hpp"
Public Member Functions
InternedString ()
const char * toCStr () const
Converts to a C-style string.
const char * getData () const
Gets the string data.
std::string_view toStringView () const
Converts to a std::string_view.
size_t size () const
Gets string length.
size_t length () const
Gets the string length.
bool isEmpty () const
Checks if the string is empty.
bool operator== (const InternedString &other) const
Pointer comparison operators for fast equality checks.
bool operator!= (const InternedString &other) const
Pointer comparison operators for fast equality checks.
bool operator< (const InternedString &other) const
Pointer comparison for ordering.
bool equals (std::string_view other) const
Compares with a std::string_view for equality.
bool isValid () const
Checks if the string is valid.
size_t getHashValue () const
Gets the hash value of the string.
std::string toString () const
Converts to a string.
operator std::string_view () const
Implicit conversion to std::string_view.
Friends
class StringInterner
Detailed Description
An interned string handle.
Represents a unique interned string stored in a StringInterner. Provides fast comparison via pointer equality and access to the underlying string data.
See also
StringInterner for managing interned strings.
Definition at line 27 of file StringInterner.hpp.
Constructor & Destructor Documentation
InternedString()
ml::InternedString::InternedString () inline
Definition at line 29 of file StringInterner.hpp.
Member Function Documentation
equals()
bool ml::InternedString::equals (std::string_view other) const inline
Compares with a std::string_view for equality.
Parameters
other The std::string_view to compare with.
Returns
true if equal, false otherwise.
See also
operator==(const InternedString &) const for pointer comparison.
Note
Use pointer comparison for best performance when possible.
Definition at line 102 of file StringInterner.hpp.
References toStringView().
getData()
const char * ml::InternedString::getData () const inline
Gets the string data.
Returns
The underlying string data.
Note
Returns nullptr if string is invalid.
See also
toCStr() for safe access.
Definition at line 45 of file StringInterner.hpp.
getHashValue()
size_t ml::InternedString::getHashValue () const inline
Gets the hash value of the string.
Returns
The hash value of the underlying data.
Note
Hash is pointer-based for fast lookup in hash tables.
Definition at line 116 of file StringInterner.hpp.
Referenced by ml::InternedStringHash::operator()().
isEmpty()
bool ml::InternedString::isEmpty () const inline
Checks if the string is empty.
Returns
true if nullptr or '\0' character, false otherwise.
Definition at line 74 of file StringInterner.hpp.
isValid()
bool ml::InternedString::isValid () const inline
Checks if the string is valid.
Returns
false if nullptr, true otherwise.
See also
isEmpty() for emptiness check.
Definition at line 109 of file StringInterner.hpp.
Referenced by ml::operator<<().
length()
size_t ml::InternedString::length () const inline
Gets the string length.
Returns
Length in characters.
Definition at line 68 of file StringInterner.hpp.
operator std::string_view()
ml::InternedString::operator std::string_view () const inline
Implicit conversion to std::string_view.
Returns
A std::string_view copy.
Definition at line 128 of file StringInterner.hpp.
References toStringView().
operator!=()
bool ml::InternedString::operator!= (const InternedString & other) const inline
Pointer comparison operators for fast equality checks.
Definition at line 86 of file StringInterner.hpp.
operator<()
bool ml::InternedString::operator< (const InternedString & other) const inline
Pointer comparison for ordering.
Definition at line 93 of file StringInterner.hpp.
operator==()
bool ml::InternedString::operator== (const InternedString & other) const inline
Pointer comparison operators for fast equality checks.
Definition at line 79 of file StringInterner.hpp.
size()
size_t ml::InternedString::size () const inline
Gets string length.
Returns
Length in characters.
Deprecated:
Use length() instead.
See also
length()
Definition at line 62 of file StringInterner.hpp.
References toStringView().
toCStr()
const char * ml::InternedString::toCStr () const inline
Converts to a C-style string.
Returns
A pointer to the null-terminated string.
Note
Returns empty string "" if data is a nullptr value.
See also
getData() for raw data access.
Definition at line 37 of file StringInterner.hpp.
toString()
std::string ml::InternedString::toString () const inline
Converts to a string.
Returns
A std::string copy.
Definition at line 122 of file StringInterner.hpp.
References toStringView().
Referenced by ml::FullSourceLoc::getFilename().
toStringView()
std::string_view ml::InternedString::toStringView () const inline
Converts to a std::string_view.
Returns
A std::string_view copy.
Note
Returns empty view if data is a nullptr value.
Definition at line 52 of file StringInterner.hpp.
Referenced by equals(), ml::FileEntry::getFilenameView(), operator std::string_view(), ml::operator<<(), ml::operator<<(), size(), and toString().
Friends And Related Symbol Documentation
StringInterner
friend class StringInterner friend
Definition at line 131 of file StringInterner.hpp.
The documentation for this class was generated from the following file:
include/ml/Basic/StringInterner.hpp