my-lang: ml::FileEntry Class Reference
ml::FileEntry Class Reference
Represents the contents of a file in memory.
#include <FileManager.hpp>
Public Member Functions
FileEntry (InternedString filename, std::unique_ptr< char[]> data, size_t size, time_t modTime)
~FileEntry ()=default
FileEntry (const FileEntry &)=delete
FileEntry & operator= (const FileEntry &)=delete
InternedString getFilename () const
std::string_view getFilenameView () const
const char * getData () const
size_t getSize () const
time_t getModificationTime () const
const char * getBufferStart () const
const char * getBufferEnd () const
void addRef ()
Reference counting for shared ownership.
bool removeRef ()
uint32_t getRefCount () const
Detailed Description
Represents the contents of a file in memory.
Definition at line 15 of file FileManager.hpp.
Constructor & Destructor Documentation
FileEntry() [1/2]
ml::FileEntry::FileEntry (InternedString filename, std::unique_ptr< char[]> data, size_t size, time_t modTime) inline
Definition at line 17 of file FileManager.hpp.
~FileEntry()
ml::FileEntry::~FileEntry () default
FileEntry() [2/2]
ml::FileEntry::FileEntry (const FileEntry &) delete
Member Function Documentation
addRef()
void ml::FileEntry::addRef () inline
Reference counting for shared ownership.
Definition at line 40 of file FileManager.hpp.
getBufferEnd()
const char * ml::FileEntry::getBufferEnd () const inline
Definition at line 37 of file FileManager.hpp.
getBufferStart()
const char * ml::FileEntry::getBufferStart () const inline
Get a null-terminated view of the buffer. Note: The buffer is guaranteed to have a null terminator.
Definition at line 36 of file FileManager.hpp.
Referenced by ml::SourceManager::getCharacterData(), and ml::Lexer::Lexer().
getData()
const char * ml::FileEntry::getData () const inline
Definition at line 30 of file FileManager.hpp.
getFilename()
InternedString ml::FileEntry::getFilename () const inline
Definition at line 28 of file FileManager.hpp.
Referenced by ml::SourceManager::getFilename(), and ml::SourceManager::getFilename().
getFilenameView()
std::string_view ml::FileEntry::getFilenameView () const inline
Definition at line 29 of file FileManager.hpp.
References ml::InternedString::toStringView().
Referenced by ml::SourceManager::getFilenameView(), and ml::SourceManager::getFilenameView().
getModificationTime()
time_t ml::FileEntry::getModificationTime () const inline
Definition at line 32 of file FileManager.hpp.
getRefCount()
uint32_t ml::FileEntry::getRefCount () const inline
Definition at line 42 of file FileManager.hpp.
getSize()
size_t ml::FileEntry::getSize () const inline
Definition at line 31 of file FileManager.hpp.
Referenced by ml::SourceManager::getCharacterData(), ml::Lexer::Lexer(), and ml::tokenizeFile().
operator=()
FileEntry & ml::FileEntry::operator= (const FileEntry &) delete
removeRef()
bool ml::FileEntry::removeRef () inline
Definition at line 41 of file FileManager.hpp.
The documentation for this class was generated from the following file:
include/ml/Managers/FileManager.hpp