my-lang: ml::TextDiagnosticConsumer Class Reference
ml::TextDiagnosticConsumer Class Reference
Built-in text diagnostic consumer.
#include <DiagnosticManager.hpp>
Public Member Functions
TextDiagnosticConsumer (std::ostream &os, bool showColors=true)
void handleDiagnostic (const Diagnostic &diag, const DiagnosticInfo &info, const SourceManager *srcMgr) override
Called to handle a single diagnostic.
Public Member Functions inherited from ml::DiagnosticConsumer
virtual ~DiagnosticConsumer ()=default
virtual void beginSourceFile ()
Called before processing a batch of diagnostics.
virtual void endSourceFile ()
Called after processing a batch of diagnostics.
virtual void finish ()
Called when diagnostics are finished.
Detailed Description
Built-in text diagnostic consumer.
Definition at line 145 of file DiagnosticManager.hpp.
Constructor & Destructor Documentation
TextDiagnosticConsumer()
ml::TextDiagnosticConsumer::TextDiagnosticConsumer (std::ostream & os, bool showColors = true) inline explicit
Definition at line 147 of file DiagnosticManager.hpp.
Member Function Documentation
handleDiagnostic()
void ml::TextDiagnosticConsumer::handleDiagnostic (const Diagnostic & diag, const DiagnosticInfo & info, const SourceManager * srcMgr) override virtual
Called to handle a single diagnostic.
Implements ml::DiagnosticConsumer.
Definition at line 193 of file DiagnosticManager.cpp.
References ml::DiagnosticInfo::DetailedMessage, ml::Error, ml::Fatal, ml::Diagnostic::getArguments(), ml::FullSourceLoc::getFilename(), ml::Diagnostic::getFixItHints(), ml::SourceManager::getFullLoc(), ml::Diagnostic::getLocation(), ml::Diagnostic::getRanges(), ml::SourceLocation::isValid(), ml::DiagnosticInfo::Level, ml::Note, and ml::Warning.
The documentation for this class was generated from the following files:
include/ml/Managers/DiagnosticManager.hpp
src/Managers/DiagnosticManager.cpp