my-lang: ml::TokenManager Class Reference
ml::TokenManager Class Reference
Token manager for efficient token storage and retrieval.
#include <Lexer.hpp>
Classes
class TokenStream
Token stream operations.
Public Member Functions
TokenManager (size_t initialCapacity=1024)
~TokenManager ()
TokenManager (const TokenManager &)=delete
TokenManager & operator= (const TokenManager &)=delete
TokenManager (TokenManager &&) noexcept
TokenManager & operator= (TokenManager &&) noexcept
void addToken (const Token &token)
Add a token to the manager.
void addToken (Token &&token)
const Token & getToken (size_t index) const
Get token by index.
Token & getToken (size_t index)
size_t getTokenCount () const
Get number of tokens.
bool empty () const
Check if empty.
void clear ()
Clear all tokens.
void reserve (size_t capacity)
Reserve capacity for tokens.
std::vector< Token >::iterator begin ()
Get iterator access.
std::vector< Token >::iterator end ()
std::vector< Token >::const_iterator begin () const
std::vector< Token >::const_iterator end () const
std::vector< Token >::const_iterator cbegin () const
std::vector< Token >::const_iterator cend () const
std::vector< size_t > findTokensInRange (SourceRange range) const
Find tokens by location.
size_t findTokenAtLocation (SourceLocation loc) const
std::vector< size_t > findTokensByKind (TokenKind kind) const
Get tokens by kind.
TokenStream createStream () const
Create a token stream.
void printTokens (std::ostream &os) const
Print all tokens (for debugging)
size_t getMemoryUsage () const
Get memory usage.
Detailed Description
Token manager for efficient token storage and retrieval.
Definition at line 211 of file Lexer.hpp.
Constructor & Destructor Documentation
TokenManager() [1/3]
ml::TokenManager::TokenManager (size_t initialCapacity = 1024) explicit
Definition at line 1343 of file Lexer.cpp.
~TokenManager()
ml::TokenManager::~TokenManager () default
TokenManager() [2/3]
ml::TokenManager::TokenManager (const TokenManager &) delete
TokenManager() [3/3]
ml::TokenManager::TokenManager (TokenManager && other) noexcept
Definition at line 1349 of file Lexer.cpp.
Member Function Documentation
addToken() [1/2]
void ml::TokenManager::addToken (const Token & token)
Add a token to the manager.
Definition at line 1363 of file Lexer.cpp.
addToken() [2/2]
void ml::TokenManager::addToken (Token && token)
Definition at line 1368 of file Lexer.cpp.
begin() [1/2]
std::vector< Token >::iterator ml::TokenManager::begin () inline
Get iterator access.
Definition at line 243 of file Lexer.hpp.
begin() [2/2]
std::vector< Token >::const_iterator ml::TokenManager::begin () const inline
Definition at line 245 of file Lexer.hpp.
cbegin()
std::vector< Token >::const_iterator ml::TokenManager::cbegin () const inline
Definition at line 247 of file Lexer.hpp.
cend()
std::vector< Token >::const_iterator ml::TokenManager::cend () const inline
Definition at line 248 of file Lexer.hpp.
clear()
void ml::TokenManager::clear ()
Clear all tokens.
Definition at line 1379 of file Lexer.cpp.
createStream()
TokenStream ml::TokenManager::createStream () const inline
Create a token stream.
Definition at line 276 of file Lexer.hpp.
empty()
bool ml::TokenManager::empty () const inline
Check if empty.
Definition at line 234 of file Lexer.hpp.
end() [1/2]
std::vector< Token >::iterator ml::TokenManager::end () inline
Definition at line 244 of file Lexer.hpp.
end() [2/2]
std::vector< Token >::const_iterator ml::TokenManager::end () const inline
Definition at line 246 of file Lexer.hpp.
findTokenAtLocation()
size_t ml::TokenManager::findTokenAtLocation (SourceLocation loc) const
Definition at line 1423 of file Lexer.cpp.
References ml::SourceRange::getBegin(), ml::SourceRange::getEnd(), ml::SourceLocation::getRawEncoding(), and ml::Token::getSourceRange().
findTokensByKind()
std::vector< size_t > ml::TokenManager::findTokensByKind (TokenKind kind) const
Get tokens by kind.
Definition at line 1437 of file Lexer.cpp.
findTokensInRange()
std::vector< size_t > ml::TokenManager::findTokensInRange (SourceRange range) const
Find tokens by location.
Definition at line 1385 of file Lexer.cpp.
References ml::SourceRange::getBegin(), ml::SourceRange::getEnd(), and ml::SourceLocation::getRawEncoding().
getMemoryUsage()
size_t ml::TokenManager::getMemoryUsage () const
Get memory usage.
Definition at line 1496 of file Lexer.cpp.
getToken() [1/2]
Token & ml::TokenManager::getToken (size_t index)
Definition at line 1377 of file Lexer.cpp.
getToken() [2/2]
const Token & ml::TokenManager::getToken (size_t index) const
Get token by index.
Definition at line 1373 of file Lexer.cpp.
Referenced by ml::TokenManager::TokenStream::current().
getTokenCount()
size_t ml::TokenManager::getTokenCount () const inline
Get number of tokens.
Definition at line 231 of file Lexer.hpp.
Referenced by ml::TokenManager::TokenStream::current(), and ml::TokenManager::TokenStream::isAtEnd().
operator=() [1/2]
TokenManager & ml::TokenManager::operator= (const TokenManager &) delete
operator=() [2/2]
TokenManager & ml::TokenManager::operator= (TokenManager && other) noexcept
Definition at line 1354 of file Lexer.cpp.
printTokens()
void ml::TokenManager::printTokens (std::ostream & os) const
Print all tokens (for debugging)
Definition at line 1489 of file Lexer.cpp.
reserve()
void ml::TokenManager::reserve (size_t capacity) inline
Reserve capacity for tokens.
Definition at line 240 of file Lexer.hpp.
The documentation for this class was generated from the following files:
include/ml/Parse/Lexer.hpp
src/Parse/Lexer.cpp