my-lang: ml::FileManager Class Reference
ml::FileManager Class Reference
#include <FileManager.hpp>
Public Member Functions
FileManager (StringInterner &interner)
~FileManager ()
FileManager (const FileManager &)=delete
FileManager & operator= (const FileManager &)=delete
FileManager (FileManager &&) noexcept
FileManager & operator= (FileManager &&) noexcept
std::shared_ptr< FileEntry > getFile (const std::string &filename)
std::pair< std::shared_ptr< FileEntry >, std::error_code > getFileWithError (const std::string &filename)
Get a file entry, with error information if it fails.
bool fileExists (const std::string &filename) const
Check if a file exists without loading it.
std::pair< size_t, std::error_code > getFileSize (const std::string &filename) const
Get the size of a file without loading it.
std::pair< time_t, std::error_code > getFileModTime (const std::string &filename) const
Get file modification time.
void clearCache ()
void removeFromCache (const std::string &filename)
Remove a specific file from the cache.
void setMaxCacheSize (size_t maxSize)
size_t getMaxCacheSize () const
size_t getCurrentCacheSize () const
Get current cache size in bytes.
FileManagerStats getStats () const
Get statistics about file operations.
void setMemoryMappingEnabled (bool enabled)
Enable or disable memory mapping for large files.
bool isMemoryMappingEnabled () const
void setMemoryMappingThreshold (size_t threshold)
Set the threshold size for memory mapping (default: 64KB).
size_t getMemoryMappingThreshold () const
Detailed Description
Manages file loading, caching, and memory mapping for the compiler. This class is thread-safe and designed to handle large numbers of files efficiently.
Definition at line 64 of file FileManager.hpp.
Constructor & Destructor Documentation
FileManager() [1/3]
ml::FileManager::FileManager (StringInterner & interner) explicit
Definition at line 21 of file FileManager.cpp.
~FileManager()
ml::FileManager::~FileManager ()
Definition at line 23 of file FileManager.cpp.
References clearCache().
FileManager() [2/3]
ml::FileManager::FileManager (const FileManager &) delete
FileManager() [3/3]
ml::FileManager::FileManager (FileManager && other) noexcept
Definition at line 25 of file FileManager.cpp.
Member Function Documentation
clearCache()
void ml::FileManager::clearCache ()
Clear the file cache. This will invalidate all previously returned FileEntry pointers.
Definition at line 156 of file FileManager.cpp.
References ml::FileManagerStats::fileCacheCount.
Referenced by ~FileManager().
fileExists()
bool ml::FileManager::fileExists (const std::string & filename) const
Check if a file exists without loading it.
Definition at line 94 of file FileManager.cpp.
References ml::StringInterner::intern().
getCurrentCacheSize()
size_t ml::FileManager::getCurrentCacheSize () const
Get current cache size in bytes.
Definition at line 174 of file FileManager.cpp.
getFile()
std::shared_ptr< FileEntry > ml::FileManager::getFile (const std::string & filename)
Get a file entry for the specified filename. Returns nullptr if the file cannot be opened or read. The returned pointer remains valid until the FileManager is destroyed or clearCache() is called.
Definition at line 44 of file FileManager.cpp.
References getFileWithError().
Referenced by main().
getFileModTime()
std::pair< time_t, std::error_code > ml::FileManager::getFileModTime (const std::string & filename) const
Get file modification time.
Definition at line 132 of file FileManager.cpp.
References ml::StringInterner::intern().
getFileSize()
std::pair< size_t, std::error_code > ml::FileManager::getFileSize (const std::string & filename) const
Get the size of a file without loading it.
Definition at line 110 of file FileManager.cpp.
References ml::StringInterner::intern().
getFileWithError()
std::pair< std::shared_ptr< FileEntry >, std::error_code > ml::FileManager::getFileWithError (const std::string & filename)
Get a file entry, with error information if it fails.
Definition at line 50 of file FileManager.cpp.
References ml::FileManagerStats::cacheHitCount, ml::FileManagerStats::cacheMissCount, ml::FileManagerStats::fileCacheCount, and ml::StringInterner::intern().
Referenced by ml::SourceManager::createFileIDWithError(), and getFile().
getMaxCacheSize()
size_t ml::FileManager::getMaxCacheSize () const inline
Definition at line 106 of file FileManager.hpp.
getMemoryMappingThreshold()
size_t ml::FileManager::getMemoryMappingThreshold () const inline
Definition at line 122 of file FileManager.hpp.
getStats()
FileManagerStats ml::FileManager::getStats () const
Get statistics about file operations.
Definition at line 185 of file FileManager.cpp.
isMemoryMappingEnabled()
bool ml::FileManager::isMemoryMappingEnabled () const inline
Definition at line 116 of file FileManager.hpp.
operator=() [1/2]
FileManager & ml::FileManager::operator= (const FileManager &) delete
operator=() [2/2]
FileManager & ml::FileManager::operator= (FileManager && other) noexcept
Definition at line 32 of file FileManager.cpp.
removeFromCache()
void ml::FileManager::removeFromCache (const std::string & filename)
Remove a specific file from the cache.
Definition at line 162 of file FileManager.cpp.
References ml::FileManagerStats::fileCacheCount, and ml::StringInterner::intern().
setMaxCacheSize()
void ml::FileManager::setMaxCacheSize (size_t maxSize) inline
Set the maximum cache size in bytes. Files will be evicted when this limit is exceeded.
Definition at line 105 of file FileManager.hpp.
setMemoryMappingEnabled()
void ml::FileManager::setMemoryMappingEnabled (bool enabled) inline
Enable or disable memory mapping for large files.
Definition at line 115 of file FileManager.hpp.
setMemoryMappingThreshold()
void ml::FileManager::setMemoryMappingThreshold (size_t threshold) inline
Set the threshold size for memory mapping (default: 64KB).
Definition at line 119 of file FileManager.hpp.
The documentation for this class was generated from the following files:
include/ml/Managers/FileManager.hpp
src/Managers/FileManager.cpp