my-lang: ml::TokenManager::TokenStream Class Reference
ml::TokenManager::TokenStream Class Reference
Token stream operations.
#include <Lexer.hpp>
Public Member Functions
TokenStream (const TokenManager &mgr)
const Token & current () const
const Token & peek (size_t offset=1) const
void advance ()
bool isAtEnd () const
void reset ()
size_t getIndex () const
void setIndex (size_t index)
Detailed Description
Token stream operations.
Definition at line 258 of file Lexer.hpp.
Constructor & Destructor Documentation
TokenStream()
ml::TokenManager::TokenStream::TokenStream (const TokenManager & mgr) inline explicit
Definition at line 260 of file Lexer.hpp.
Member Function Documentation
advance()
void ml::TokenManager::TokenStream::advance ()
Definition at line 1483 of file Lexer.cpp.
current()
const Token & ml::TokenManager::TokenStream::current () const
Definition at line 1466 of file Lexer.cpp.
References ml::EndOfFile, ml::TokenManager::getToken(), and ml::TokenManager::getTokenCount().
getIndex()
size_t ml::TokenManager::TokenStream::getIndex () const inline
Definition at line 267 of file Lexer.hpp.
isAtEnd()
bool ml::TokenManager::TokenStream::isAtEnd () const inline
Definition at line 265 of file Lexer.hpp.
References ml::TokenManager::getTokenCount().
peek()
const Token & ml::TokenManager::TokenStream::peek (size_t offset = 1) const
Definition at line 1474 of file Lexer.cpp.
References ml::EndOfFile.
reset()
void ml::TokenManager::TokenStream::reset () inline
Definition at line 266 of file Lexer.hpp.
setIndex()
void ml::TokenManager::TokenStream::setIndex (size_t index) inline
Definition at line 268 of file Lexer.hpp.
The documentation for this class was generated from the following files:
include/ml/Parse/Lexer.hpp
src/Parse/Lexer.cpp