my-lang: ml::FileID Class Reference
ml::FileID Class Reference
Represents a unique identifier for a file in the source manager.
#include <SourceLocation.hpp>
Public Member Functions
FileID ()
bool isValid () const
bool isInvalid () const
bool operator== (const FileID &RHS) const
bool operator!= (const FileID &RHS) const
bool operator< (const FileID &RHS) const
uint32_t getHashValue () const
Static Public Member Functions
static FileID getInvalidID ()
Friends
class SourceManager
Detailed Description
Represents a unique identifier for a file in the source manager.
Definition at line 12 of file SourceLocation.hpp.
Constructor & Destructor Documentation
FileID()
ml::FileID::FileID () inline
Definition at line 14 of file SourceLocation.hpp.
Referenced by getInvalidID().
Member Function Documentation
getHashValue()
uint32_t ml::FileID::getHashValue () const inline
Definition at line 25 of file SourceLocation.hpp.
Referenced by ml::SourceManager::advanceSourceLocation(), ml::SourceManager::getColumnNumber(), ml::SourceManager::getFileEntry(), ml::SourceManager::getFileID(), ml::SourceManager::getFileOffset(), ml::SourceManager::getLineAndColumn(), ml::SourceManager::getLineNumber(), ml::SourceManager::getLocForEndOfFile(), ml::SourceManager::getLocForFileOffset(), ml::SourceManager::getLocForStartOfFile(), and ml::operator<<().
getInvalidID()
static FileID ml::FileID::getInvalidID () inline static
Definition at line 19 of file SourceLocation.hpp.
References FileID().
Referenced by ml::SourceManager::createFileIDWithError(), ml::FullSourceLoc::getFileID(), ml::SourceManager::getFileID(), and ml::LocationCache::invalidate().
isInvalid()
bool ml::FileID::isInvalid () const inline
Definition at line 17 of file SourceLocation.hpp.
Referenced by ml::SourceManager::advanceSourceLocation(), ml::SourceManager::getColumnNumber(), ml::SourceManager::getFileEntry(), ml::SourceManager::getFileOffset(), ml::SourceManager::getLineAndColumn(), ml::SourceManager::getLineNumber(), ml::SourceManager::getLocForEndOfFile(), ml::SourceManager::getLocForFileOffset(), and ml::SourceManager::getLocForStartOfFile().
isValid()
bool ml::FileID::isValid () const inline
Definition at line 16 of file SourceLocation.hpp.
Referenced by ml::SourceManager::getColumnNumber(), ml::SourceManager::getFileID(), ml::SourceManager::getLineNumber(), and ml::SourceManager::isValidSourceLocation().
operator!=()
bool ml::FileID::operator!= (const FileID & RHS) const inline
Definition at line 22 of file SourceLocation.hpp.
operator<()
bool ml::FileID::operator< (const FileID & RHS) const inline
Definition at line 23 of file SourceLocation.hpp.
operator==()
bool ml::FileID::operator== (const FileID & RHS) const inline
Definition at line 21 of file SourceLocation.hpp.
Friends And Related Symbol Documentation
SourceManager
friend class SourceManager friend
Definition at line 28 of file SourceLocation.hpp.
The documentation for this class was generated from the following file:
include/ml/Basic/SourceLocation.hpp