my-lang: ml::Diagnostic Class Reference
ml::Diagnostic Class Reference
A single diagnostic instance with location and arguments.
#include <DiagnosticManager.hpp>
Classes
struct FixItHint
Public Member Functions
Diagnostic (DiagnosticID id, SourceLocation loc=SourceLocation())
Diagnostic & addArg (std::string_view arg)
Add string argument for diagnostic message formatting.
Diagnostic & addRange (SourceRange range)
Add source range for highlighting.
Diagnostic & addFixIt (SourceRange range, std::string_view replacement)
Add fix-it hint.
DiagnosticID getID () const
SourceLocation getLocation () const
const std::vector< std::string > & getArguments () const
const std::vector< SourceRange > & getRanges () const
const std::vector< FixItHint > & getFixItHints () const
Detailed Description
A single diagnostic instance with location and arguments.
Definition at line 58 of file DiagnosticManager.hpp.
Constructor & Destructor Documentation
Diagnostic()
ml::Diagnostic::Diagnostic (DiagnosticID id, SourceLocation loc = SourceLocation()) inline
Definition at line 60 of file DiagnosticManager.hpp.
Member Function Documentation
addArg()
Diagnostic & ml::Diagnostic::addArg (std::string_view arg) inline
Add string argument for diagnostic message formatting.
Definition at line 64 of file DiagnosticManager.hpp.
Referenced by ml::DiagnosticManager::report(), and ml::DiagnosticManager::report().
addFixIt()
Diagnostic & ml::Diagnostic::addFixIt (SourceRange range, std::string_view replacement) inline
Add fix-it hint.
Definition at line 76 of file DiagnosticManager.hpp.
addRange()
Diagnostic & ml::Diagnostic::addRange (SourceRange range) inline
Add source range for highlighting.
Definition at line 70 of file DiagnosticManager.hpp.
getArguments()
const std::vector< std::string > & ml::Diagnostic::getArguments () const inline
Definition at line 83 of file DiagnosticManager.hpp.
Referenced by ml::TextDiagnosticConsumer::handleDiagnostic(), and ml::JSONDiagnosticConsumer::handleDiagnostic().
getFixItHints()
const std::vector< FixItHint > & ml::Diagnostic::getFixItHints () const inline
Definition at line 94 of file DiagnosticManager.hpp.
Referenced by ml::TextDiagnosticConsumer::handleDiagnostic().
getID()
DiagnosticID ml::Diagnostic::getID () const inline
Definition at line 81 of file DiagnosticManager.hpp.
Referenced by ml::JSONDiagnosticConsumer::handleDiagnostic(), and ml::DiagnosticManager::report().
getLocation()
SourceLocation ml::Diagnostic::getLocation () const inline
Definition at line 82 of file DiagnosticManager.hpp.
Referenced by ml::TextDiagnosticConsumer::handleDiagnostic(), and ml::JSONDiagnosticConsumer::handleDiagnostic().
getRanges()
const std::vector< SourceRange > & ml::Diagnostic::getRanges () const inline
Definition at line 84 of file DiagnosticManager.hpp.
Referenced by ml::TextDiagnosticConsumer::handleDiagnostic().
The documentation for this class was generated from the following file:
include/ml/Managers/DiagnosticManager.hpp