var hierarchy =
[
    [ "ml::ArenaAllocator", "classml_1_1ArenaAllocator.html", null ],
    [ "ml::ArenaChunk", "structml_1_1ArenaChunk.html", null ],
    [ "ml::ArenaScope", "classml_1_1ArenaScope.html", null ],
    [ "ml::ArenaStats", "structml_1_1ArenaStats.html", null ],
    [ "ml::ArenaSTLAllocator< T >", "classml_1_1ArenaSTLAllocator.html", null ],
    [ "ml::BatchTokenizer", "classml_1_1BatchTokenizer.html", null ],
    [ "ml::StringInterner::const_iterator", "classml_1_1StringInterner_1_1const__iterator.html", null ],
    [ "ml::Diagnostic", "classml_1_1Diagnostic.html", null ],
    [ "ml::DiagnosticConsumer", "classml_1_1DiagnosticConsumer.html", [
      [ "ml::JSONDiagnosticConsumer", "classml_1_1JSONDiagnosticConsumer.html", null ],
      [ "ml::TextDiagnosticConsumer", "classml_1_1TextDiagnosticConsumer.html", null ]
    ] ],
    [ "ml::DiagnosticInfo", "structml_1_1DiagnosticInfo.html", null ],
    [ "ml::DiagnosticManager", "classml_1_1DiagnosticManager.html", null ],
    [ "ml::DiagnosticStats", "structml_1_1DiagnosticStats.html", null ],
    [ "ml::DiagnosticSuppressor", "classml_1_1DiagnosticSuppressor.html", null ],
    [ "ml::FileEntry", "classml_1_1FileEntry.html", null ],
    [ "ml::FileID", "classml_1_1FileID.html", null ],
    [ "ml::FileInfo", "structml_1_1FileInfo.html", null ],
    [ "ml::FileManager", "classml_1_1FileManager.html", null ],
    [ "ml::FileManagerStats", "structml_1_1FileManagerStats.html", null ],
    [ "ml::Diagnostic::FixItHint", "structml_1_1Diagnostic_1_1FixItHint.html", null ],
    [ "ml::FullSourceLoc", "structml_1_1FullSourceLoc.html", null ],
    [ "std::hash< ml::InternedString >", "structstd_1_1hash_3_01ml_1_1InternedString_01_4.html", null ],
    [ "ml::InternedString", "classml_1_1InternedString.html", null ],
    [ "ml::InternedStringHash", "structml_1_1InternedStringHash.html", null ],
    [ "ml::Lexer", "classml_1_1Lexer.html", null ],
    [ "ml::LexerOptions", "structml_1_1LexerOptions.html", null ],
    [ "ml::LexerStats", "structml_1_1LexerStats.html", null ],
    [ "ml::ArenaSTLAllocator< T >::rebind< U >", "structml_1_1ArenaSTLAllocator_1_1rebind.html", null ],
    [ "ml::SourceLocation", "classml_1_1SourceLocation.html", null ],
    [ "ml::SourceManager", "classml_1_1SourceManager.html", null ],
    [ "ml::SourceManagerStats", "structml_1_1SourceManagerStats.html", null ],
    [ "ml::SourceRange", "classml_1_1SourceRange.html", null ],
    [ "ml::StringInterner", "classml_1_1StringInterner.html", null ],
    [ "ml::StringInternerStats", "structml_1_1StringInternerStats.html", null ],
    [ "ml::Token", "classml_1_1Token.html", null ],
    [ "ml::TokenInfo", "classml_1_1TokenInfo.html", null ],
    [ "ml::TokenManager", "classml_1_1TokenManager.html", null ],
    [ "ml::TokenManager::TokenStream", "classml_1_1TokenManager_1_1TokenStream.html", null ]
];