my-lang: ml Namespace Reference
ml Namespace Reference
Classes
class ArenaAllocator
An allocator using arena allocation strategy.
struct ArenaChunk
A chunk of memory managed by ArenaAllocator.
class ArenaScope
A scope guard for arena allocation.
struct ArenaStats
A container for statistics about ArenaAllocator usage.
class ArenaSTLAllocator
STL-compatible allocator using ArenaAllocator.
class BatchTokenizer
High-performance batch tokenization for large sources.
class Diagnostic
A single diagnostic instance with location and arguments.
class DiagnosticConsumer
Consumer interface for diagnostic output.
struct DiagnosticInfo
Individual diagnostic definition.
class DiagnosticManager
Main diagnostic manager class.
struct DiagnosticStats
Statistics about diagnostic reporting.
class DiagnosticSuppressor
RAII helper for suppressing diagnostics in a scope.
class FileEntry
Represents the contents of a file in memory.
class FileID
A unique identifier for a source file.
struct FileInfo
Information about a loaded file in the source manager.
class FileManager
struct FileManagerStats
Statistics about file operations.
struct FullSourceLoc
A source location with additional context from SourceManager.
class InternedString
An interned string handle.
struct InternedStringHash
Hash function for InternedString.
class JSONDiagnosticConsumer
Built-in JSON diagnostic consumer.
struct KeywordEntry
class Lexer
Main lexer class for tokenizing source code.
struct LexerOptions
Lexer options and configuration.
struct LexerStats
Statistics about lexer performance.
struct LocationCache
class SourceLocation
A source location within a file.
class SourceManager
struct SourceManagerStats
Statistics about source manager operations.
class SourceRange
A range between two source locations.
class StringInterner
A string interner for deduplicating strings.
struct StringInternerStats
Statistics about the StringInterner.
class TextDiagnosticConsumer
Built-in text diagnostic consumer.
class Token
A single token with location and metadata.
class TokenInfo
Token information and utilities.
class TokenManager
Token manager for efficient token storage and retrieval.
Typedefs
template<typename T >
using ArenaVector = std::vector< T, ArenaSTLAllocator< T > >
Convenience aliases for STL containers with arena allocation.
template<typename T >
using ArenaDeque = std::deque< T, ArenaSTLAllocator< T > >
STL deque using arena allocation.
template<typename T >
using ArenaList = std::list< T, ArenaSTLAllocator< T > >
STL list using arena allocation.
using PreprocessorCallback = std::function< void(std::string_view directive, SourceLocation loc)>
Callback for handling preprocessor directives.
Enumerations
enum class DiagnosticLevel { Note , Warning , Error , Fatal }
Severity levels for diagnostics.
enum class DiagnosticKind {
System , Lexical , Syntax , Semantic ,
Type , Codegen , Link , Runtime
}
Categories of diagnostics.
enum class DiagnosticID : uint32_t { Diagnostic , NumDiagnostics }
Unique identifier for each diagnostic type.
enum class DiagnosticFormat { Text , JSON , XML , SARIF }
Output format for diagnostics.
enum class TokenKind : uint16_t {
Unknown , EndOfFile , Integer , Float ,
String , Character , Boolean , Identifier ,
Auto , Break , Case , Const ,
Continue , Default , Do , Else ,
Enum , Extern , False , For ,
Fn , If , Import , Let ,
Mod , Mut , Null , Return ,
Struct , Switch , True , Type ,
Var , While , Plus , Minus ,
Star , Slash , Percent , Equal ,
PlusEqual , MinusEqual , StarEqual , SlashEqual ,
PercentEqual , EqualEqual , NotEqual , Less ,
LessEqual , Greater , GreaterEqual , AmpAmp ,
PipePipe , Exclaim , Amp , Pipe ,
Caret , Tilde , LesserLesser , GreaterGreater ,
PlusPlus , MinusMinus , LeftParen , RightParen ,
LeftBrace , RightBrace , LeftBracket , RightBracket ,
Semicolon , Comma , Dot , Arrow ,
ColonColon , Colon , Question , At ,
Hash , Backslash , LineComment , BlockComment ,
Whitespace , Newline , Count
}
Token types for the language.
enum class TokenFlags : uint8_t {
None = 0 , AtStartOfLine = 1 << 0 , HasLeadingSpace = 1 << 1 , NeedsCleaning = 1 << 2 ,
IsKeyword = 1 << 3
}
Token flags for additional information.
Functions
std::ostream & operator<< (std::ostream &os, const InternedString &str)
Stream output operator for InternedString.
std::ostream & operator<< (std::ostream &os, SourceLocation loc)
Helper functions for working with source locations.
std::ostream & operator<< (std::ostream &os, FileID fid)
std::vector< Token > tokenizeString (std::string_view source, StringInterner &interner, DiagnosticManager &diagMgr, const LexerOptions &opts=LexerOptions{})
Convenience function to tokenize a string.
std::vector< Token > tokenizeFile (const SourceManager &srcMgr, FileID fileID, StringInterner &interner, DiagnosticManager &diagMgr, const LexerOptions &opts=LexerOptions{})
Convenience function to tokenize a file.
TokenFlags operator| (TokenFlags lhs, TokenFlags rhs)
TokenFlags operator& (TokenFlags lhs, TokenFlags rhs)
TokenFlags & operator|= (TokenFlags &lhs, TokenFlags rhs)
std::ostream & operator<< (std::ostream &os, TokenKind kind)
Stream output for tokens.
std::ostream & operator<< (std::ostream &os, const Token &token)
bool isAlphaFast (unsigned char c)
bool isDigitFast (unsigned char c)
bool isAlnumFast (unsigned char c)
bool isWhitespaceFast (unsigned char c)
bool isNewlineFast (unsigned char c)
bool isHexDigitFast (unsigned char c)
static std::pair< const char *, size_t > skipWhitespaceSimdWithStats (const char *ptr, const char *end)
static const char * skipWhitespaceSimd (const char *ptr, const char *end)
static TokenKind getKeywordKindFast (std::string_view text)
static std::array< int, static_cast< size_t >(TokenKind::Count)> createOperatorPrecedenceTable ()
Variables
thread_local LocationCache g_location_cache
static constexpr std::array< uint8_t, 256 > CHAR_CLASS_TABLE
static constexpr std::array< std::pair< std::string_view, TokenKind >, 27 > KEYWORD_TABLE
static const char * TokenSpellings []
static const char * TokenNames []
static constexpr std::array< KeywordEntry, 26 > KEYWORD_LOOKUP_TABLE
Typedef Documentation
ArenaDeque
template<typename T > using ml::ArenaDeque = typedef std::deque<T, ArenaSTLAllocator<T> >
STL deque using arena allocation.
Template Parameters
T The type of objects in the deque.
Definition at line 540 of file ArenaAllocator.hpp.
ArenaList
template<typename T > using ml::ArenaList = typedef std::list<T, ArenaSTLAllocator<T> >
STL list using arena allocation.
Template Parameters
T The type of objects in the list.
Definition at line 546 of file ArenaAllocator.hpp.
ArenaVector
template<typename T > using ml::ArenaVector = typedef std::vector<T, ArenaSTLAllocator<T> >
Convenience aliases for STL containers with arena allocation.
STL vector using arena allocation.
Template Parameters
T The type of objects in the vector.
Definition at line 534 of file ArenaAllocator.hpp.
PreprocessorCallback
using ml::PreprocessorCallback = typedef std::function<void(std::string_view directive, SourceLocation loc)>
Callback for handling preprocessor directives.
Definition at line 64 of file Lexer.hpp.
Enumeration Type Documentation
DiagnosticFormat
enum class ml::DiagnosticFormat strong
Output format for diagnostics.
Enumerator
Text
JSON
XML
SARIF
Definition at line 117 of file DiagnosticManager.hpp.
DiagnosticID
enum class ml::DiagnosticID : uint32_t strong
Unique identifier for each diagnostic type.
Enumerator
Diagnostic
NumDiagnostics
Definition at line 48 of file DiagnosticManager.hpp.
DiagnosticKind
enum class ml::DiagnosticKind strong
Categories of diagnostics.
Enumerator
System
Lexical
Syntax
Semantic
Type
Codegen
Link
Runtime
Definition at line 23 of file DiagnosticManager.hpp.
DiagnosticLevel
enum class ml::DiagnosticLevel strong
Severity levels for diagnostics.
Enumerator
Note
Warning
Error
Fatal
Definition at line 20 of file DiagnosticManager.hpp.
TokenFlags
enum class ml::TokenFlags : uint8_t strong
Token flags for additional information.
Enumerator
None
AtStartOfLine
HasLeadingSpace
NeedsCleaning
IsKeyword
Definition at line 126 of file Token.hpp.
TokenKind
enum class ml::TokenKind : uint16_t strong
Token types for the language.
Enumerator
Unknown
EndOfFile
Integer
Float
String
Character
Boolean
Identifier
Auto
Break
Case
Const
Continue
Default
Do
Else
Enum
Extern
False
For
Fn
If
Import
Let
Mod
Mut
Null
Return
Struct
Switch
True
Type
Var
While
Plus
Minus
Star
Slash
Percent
Equal
PlusEqual
MinusEqual
StarEqual
SlashEqual
PercentEqual
EqualEqual
NotEqual
Less
LessEqual
Greater
GreaterEqual
AmpAmp
PipePipe
Exclaim
Amp
Pipe
Caret
Tilde
LesserLesser
GreaterGreater
PlusPlus
MinusMinus
LeftParen
RightParen
LeftBrace
RightBrace
LeftBracket
RightBracket
Semicolon
Comma
Dot
Arrow
ColonColon
Colon
Question
At
Hash
Backslash
LineComment
BlockComment
Whitespace
Newline
Count
Definition at line 13 of file Token.hpp.
Function Documentation
createOperatorPrecedenceTable()
static std::array< int, static_cast< size_t >(TokenKind::Count)> ml::createOperatorPrecedenceTable () static
Definition at line 279 of file Token.cpp.
References Amp, AmpAmp, Caret, Count, Equal, EqualEqual, Greater, GreaterEqual, GreaterGreater, Less, LessEqual, LesserLesser, Minus, MinusEqual, NotEqual, Percent, PercentEqual, Pipe, PipePipe, Plus, PlusEqual, Slash, SlashEqual, Star, and StarEqual.
Referenced by ml::TokenInfo::getOperatorPrecedence().
getKeywordKindFast()
static TokenKind ml::getKeywordKindFast (std::string_view text) static
Definition at line 177 of file Lexer.cpp.
References Identifier, and KEYWORD_TABLE.
isAlnumFast()
bool ml::isAlnumFast (unsigned char c) inline
Definition at line 66 of file Lexer.cpp.
References CHAR_CLASS_TABLE.
isAlphaFast()
bool ml::isAlphaFast (unsigned char c) inline
Definition at line 64 of file Lexer.cpp.
References CHAR_CLASS_TABLE.
Referenced by ml::Lexer::nextToken().
isDigitFast()
bool ml::isDigitFast (unsigned char c) inline
Definition at line 65 of file Lexer.cpp.
References CHAR_CLASS_TABLE.
Referenced by ml::Lexer::nextToken().
isHexDigitFast()
bool ml::isHexDigitFast (unsigned char c) inline
Definition at line 71 of file Lexer.cpp.
References CHAR_CLASS_TABLE.
isNewlineFast()
bool ml::isNewlineFast (unsigned char c) inline
Definition at line 70 of file Lexer.cpp.
References CHAR_CLASS_TABLE.
Referenced by ml::Lexer::nextToken(), and ml::Lexer::skipTrivialOptimized().
isWhitespaceFast()
bool ml::isWhitespaceFast (unsigned char c) inline
Definition at line 67 of file Lexer.cpp.
References CHAR_CLASS_TABLE.
Referenced by ml::Lexer::nextToken(), ml::Lexer::skipTrivialOptimized(), and skipWhitespaceSimdWithStats().
operator&()
TokenFlags ml::operator& (TokenFlags lhs, TokenFlags rhs) inline
Definition at line 139 of file Token.hpp.
operator<<() [1/5]
std::ostream & ml::operator<< (std::ostream & os, const InternedString & str) inline
Stream output operator for InternedString.
Parameters
os The output stream.
str The InternedString to output.
Returns
The output stream.
Definition at line 488 of file StringInterner.hpp.
References ml::InternedString::toStringView().
operator<<() [2/5]
std::ostream & ml::operator<< (std::ostream & os, const Token & token)
Definition at line 410 of file Token.cpp.
References ml::Token::getKind(), ml::Token::getText(), ml::TokenInfo::getTokenName(), ml::InternedString::isValid(), and ml::InternedString::toStringView().
operator<<() [3/5]
std::ostream & ml::operator<< (std::ostream & os, FileID fid) inline
Definition at line 165 of file SourceManager.hpp.
operator<<() [4/5]
std::ostream & ml::operator<< (std::ostream & os, SourceLocation loc) inline
Helper functions for working with source locations.
Definition at line 161 of file SourceManager.hpp.
operator<<() [5/5]
std::ostream & ml::operator<< (std::ostream & os, TokenKind kind)
Stream output for tokens.
Definition at line 406 of file Token.cpp.
References ml::TokenInfo::getTokenName().
operator|()
TokenFlags ml::operator| (TokenFlags lhs, TokenFlags rhs) inline
Definition at line 134 of file Token.hpp.
operator|=()
TokenFlags & ml::operator|= (TokenFlags & lhs, TokenFlags rhs) inline
Definition at line 144 of file Token.hpp.
skipWhitespaceSimd()
static const char * ml::skipWhitespaceSimd (const char * ptr, const char * end) static
Definition at line 143 of file Lexer.cpp.
References skipWhitespaceSimdWithStats().
skipWhitespaceSimdWithStats()
static std::pair< const char *, size_t > ml::skipWhitespaceSimdWithStats (const char * ptr, const char * end) static
Definition at line 75 of file Lexer.cpp.
References isWhitespaceFast().
Referenced by ml::Lexer::skipTrivialOptimized(), and skipWhitespaceSimd().
tokenizeFile()
std::vector< Token > ml::tokenizeFile (const SourceManager & srcMgr, FileID fileID, StringInterner & interner, DiagnosticManager & diagMgr, const LexerOptions & opts = LexerOptions{})
Convenience function to tokenize a file.
Definition at line 1527 of file Lexer.cpp.
References EndOfFile, ml::SourceManager::getFileEntry(), ml::Token::getKind(), ml::FileEntry::getSize(), and ml::Lexer::nextToken().
tokenizeString()
std::vector< Token > ml::tokenizeString (std::string_view source, StringInterner & interner, DiagnosticManager & diagMgr, const LexerOptions & opts = LexerOptions{})
Convenience function to tokenize a string.
Definition at line 1507 of file Lexer.cpp.
References EndOfFile, ml::Token::getKind(), and ml::Lexer::nextToken().
Referenced by ml::BatchTokenizer::tokenizeParallel().
Variable Documentation
CHAR_CLASS_TABLE
constexpr std::array<uint8_t, 256> ml::CHAR_CLASS_TABLE static constexpr
Definition at line 24 of file Lexer.cpp.
Referenced by isAlnumFast(), isAlphaFast(), isDigitFast(), isHexDigitFast(), isNewlineFast(), and isWhitespaceFast().
g_location_cache
thread_local LocationCache ml::g_location_cache
Definition at line 27 of file SourceManager.cpp.
Referenced by ml::SourceManager::getColumnNumber(), ml::SourceManager::getFileID(), ml::SourceManager::getLineNumber(), and ml::SourceManager::SourceManager().
KEYWORD_LOOKUP_TABLE
constexpr std::array<KeywordEntry, 26> ml::KEYWORD_LOOKUP_TABLE static constexpr
Initial value:
= {
    {{"auto", TokenKind::Auto},
     {"break", TokenKind::Break},
     {"case", TokenKind::Case},
     {"const", TokenKind::Const},
     {"continue", TokenKind::Continue},
     {"default", TokenKind::Default},
     {"do", TokenKind::Do},
     {"else", TokenKind::Else},
     {"enum", TokenKind::Enum},
     {"extern", TokenKind::Extern},
     {"false", TokenKind::False},
     {"for", TokenKind::For},
     {"function", TokenKind::Fn},
     {"if", TokenKind::If},
     {"import", TokenKind::Import},
     {"let", TokenKind::Let},
     {"module", TokenKind::Mod},
     {"mut", TokenKind::Mut},
     {"null", TokenKind::Null},
     {"return", TokenKind::Return},
     {"struct", TokenKind::Struct},
     {"switch", TokenKind::Switch},
     {"true", TokenKind::True},
     {"type", TokenKind::Type},
     {"var", TokenKind::Var},
     {"while", TokenKind::While}}}
Definition at line 249 of file Token.cpp.
Referenced by ml::TokenInfo::getKeywordKind().
KEYWORD_TABLE
constexpr std::array<std::pair<std::string_view, TokenKind>, 27> ml::KEYWORD_TABLE static constexpr
Initial value:
= {{{"auto", TokenKind::Auto},
                      {"break", TokenKind::Break},
                      {"case", TokenKind::Case},
                      {"const", TokenKind::Const},
                      {"continue", TokenKind::Continue},
                      {"default", TokenKind::Default},
                      {"do", TokenKind::Do},
                      {"else", TokenKind::Else},
                      {"enum", TokenKind::Enum},
                      {"extern", TokenKind::Extern},
                      {"false", TokenKind::False},
                      {"for", TokenKind::For},
                      {"fn", TokenKind::Fn},
                      {"if", TokenKind::If},
                      {"import", TokenKind::Import},
                      {"let", TokenKind::Let},
                      {"mod", TokenKind::Mod},
                      {"mut", TokenKind::Mut},
                      {"null", TokenKind::Null},
                      {"return", TokenKind::Return},
                      {"struct", TokenKind::Struct},
                      {"switch", TokenKind::Switch},
                      {"true", TokenKind::True},
                      {"type", TokenKind::Type},
                      {"var", TokenKind::Var},
                      {"while", TokenKind::While}}}
Definition at line 149 of file Lexer.cpp.
Referenced by getKeywordKindFast().
TokenNames
const char* ml::TokenNames[] static
Definition at line 124 of file Token.cpp.
Referenced by ml::TokenInfo::getTokenName().
TokenSpellings
const char* ml::TokenSpellings[] static
Definition at line 10 of file Token.cpp.
Referenced by ml::TokenInfo::getTokenSpelling().