my-lang: ml::FullSourceLoc Struct Reference
ml::FullSourceLoc Struct Reference
A source location with additional context from SourceManager.
#include "ml/Basic/SourceLocation.hpp"
Public Member Functions
FullSourceLoc ()
FullSourceLoc (SourceLocation loc, const SourceManager &sm)
bool isValid () const
Check if the FullSourceLoc is valid.
FileID getFileID () const
Get the FileID of the source location.
uint32_t getFileOffset () const
Get the file offset of the source location.
uint32_t getLineNumber () const
Get the associated FileEntry.
uint32_t getColumnNumber () const
Get the column number of the source location.
const char * getCharacterData () const
Get the character data at the source location.
std::string getFilename () const
Get the filename for the source location.
Public Attributes
SourceLocation location
The underlying source location.
const SourceManager * srcMgr
The associated SourceManager.
Detailed Description
A source location with additional context from SourceManager.
Combines a SourceLocation with a reference to the SourceManager to provide enriched information about the location, such as filename, line number, and column number.
See also
SourceLocation for basic location representation.
SourceManager for context management.
Definition at line 218 of file SourceLocation.hpp.
Constructor & Destructor Documentation
FullSourceLoc() [1/2]
ml::FullSourceLoc::FullSourceLoc () inline
Definition at line 230 of file SourceLocation.hpp.
FullSourceLoc() [2/2]
ml::FullSourceLoc::FullSourceLoc (SourceLocation loc, const SourceManager & sm) inline
Definition at line 231 of file SourceLocation.hpp.
Member Function Documentation
getCharacterData()
const char * ml::FullSourceLoc::getCharacterData () const
Get the character data at the source location.
Returns
A pointer to the character data.
Definition at line 46 of file SourceManager.cpp.
References ml::SourceManager::getCharacterData(), location, and srcMgr.
getColumnNumber()
uint32_t ml::FullSourceLoc::getColumnNumber () const
Get the column number of the source location.
Returns
The column number. 1-based
Definition at line 42 of file SourceManager.cpp.
References ml::SourceManager::getColumnNumber(), location, and srcMgr.
getFileID()
FileID ml::FullSourceLoc::getFileID () const
Get the FileID of the source location.
Returns
The FileID corresponding to the location.
Definition at line 30 of file SourceManager.cpp.
References ml::SourceManager::getFileID(), ml::FileID::getInvalidID(), location, and srcMgr.
getFilename()
std::string ml::FullSourceLoc::getFilename () const
Get the filename for the source location.
Returns
The filename as a string.
Definition at line 50 of file SourceManager.cpp.
References ml::SourceManager::getFilename(), location, srcMgr, and ml::InternedString::toString().
Referenced by ml::TextDiagnosticConsumer::handleDiagnostic(), and ml::JSONDiagnosticConsumer::handleDiagnostic().
getFileOffset()
uint32_t ml::FullSourceLoc::getFileOffset () const
Get the file offset of the source location.
Returns
The byte offset within the file.
Definition at line 34 of file SourceManager.cpp.
References ml::SourceManager::getFileOffset(), location, and srcMgr.
getLineNumber()
uint32_t ml::FullSourceLoc::getLineNumber () const
Get the associated FileEntry.
Returns
A pointer to the FileEntry for the location.
Definition at line 38 of file SourceManager.cpp.
References ml::SourceManager::getLineNumber(), location, and srcMgr.
isValid()
bool ml::FullSourceLoc::isValid () const inline
Check if the FullSourceLoc is valid.
Returns
True if both the location and SourceManager are valid.
Definition at line 238 of file SourceLocation.hpp.
References ml::SourceLocation::isValid(), location, and srcMgr.
Member Data Documentation
location
SourceLocation ml::FullSourceLoc::location
The underlying source location.
Definition at line 223 of file SourceLocation.hpp.
Referenced by getCharacterData(), getColumnNumber(), getFileID(), getFilename(), getFileOffset(), getLineNumber(), and isValid().
srcMgr
const SourceManager* ml::FullSourceLoc::srcMgr
The associated SourceManager.
Definition at line 228 of file SourceLocation.hpp.
Referenced by getCharacterData(), getColumnNumber(), getFileID(), getFilename(), getFileOffset(), getLineNumber(), and isValid().
The documentation for this struct was generated from the following files:
include/ml/Basic/SourceLocation.hpp
src/Managers/SourceManager.cpp