my-lang: ml::ArenaChunk Struct Reference
ml::ArenaChunk Struct Reference
Represents a single memory chunk in a ArenaAllocator.
#include "ml/Basic/ArenaAllocator.hpp"
Public Member Functions
ArenaChunk (size_t size)
ArenaChunk (const ArenaChunk &)=delete
ArenaChunk & operator= (const ArenaChunk &)=delete
ArenaChunk (ArenaChunk &&)=default
ArenaChunk & operator= (ArenaChunk &&)=default
char * getUnused () const
Gets a pointer to the unused memory in this chunk.
size_t getRemaining () const
Gets the number of remaining bytes in this chunk.
bool canFit (size_t size) const
Checks if the chunk can fit a requested size.
void * allocate (size_t size, size_t alignment)
Allocates memory within this chunk.
Public Attributes
std::unique_ptr< char[]> memory
The memory block for this chunk.
size_t size
The total size of the chunk in bytes.
size_t used
The amount of memory used in bytes.
Detailed Description
Represents a single memory chunk in a ArenaAllocator.
Encapsulates a contiguous block of memory managed by the ArenaAllocator. It tracks the size of the chunk, the amount of memory used, and provides methods for allocation within the chunk.
See also
ArenaAllocator for context.
Definition at line 111 of file ArenaAllocator.hpp.
Constructor & Destructor Documentation
ArenaChunk() [1/3]
ml::ArenaChunk::ArenaChunk (size_t size) inline
Definition at line 129 of file ArenaAllocator.hpp.
ArenaChunk() [2/3]
ml::ArenaChunk::ArenaChunk (const ArenaChunk &) delete
ArenaChunk() [3/3]
ml::ArenaChunk::ArenaChunk (ArenaChunk &&) default
Member Function Documentation
allocate()
void * ml::ArenaChunk::allocate (size_t size, size_t alignment) inline
Allocates memory within this chunk.
Parameters
size The size of memory to allocate
alignment The required alignment
Returns
A pointer to the allocated memory or nullptr if allocation fails.
Definition at line 163 of file ArenaAllocator.hpp.
References getRemaining(), getUnused(), size, and used.
canFit()
bool ml::ArenaChunk::canFit (size_t size) const inline
Checks if the chunk can fit a requested size.
Parameters
size The size to check
Returns
True if the chunk can accommodate the requested size
Definition at line 155 of file ArenaAllocator.hpp.
References getRemaining(), and size.
getRemaining()
size_t ml::ArenaChunk::getRemaining () const inline
Gets the number of remaining bytes in this chunk.
Returns
The number of remaining bytes
Definition at line 148 of file ArenaAllocator.hpp.
References size, and used.
Referenced by allocate(), and canFit().
getUnused()
char * ml::ArenaChunk::getUnused () const inline
Gets a pointer to the unused memory in this chunk.
Returns
A pointer to the start of unused memory
Definition at line 142 of file ArenaAllocator.hpp.
References memory, and used.
Referenced by allocate().
operator=() [1/2]
ArenaChunk & ml::ArenaChunk::operator= (ArenaChunk &&) default
operator=() [2/2]
ArenaChunk & ml::ArenaChunk::operator= (const ArenaChunk &) delete
Member Data Documentation
memory
std::unique_ptr<char[]> ml::ArenaChunk::memory
The memory block for this chunk.
A unique pointer managing the memory allocated for this chunk.
Definition at line 117 of file ArenaAllocator.hpp.
Referenced by getUnused().
size
size_t ml::ArenaChunk::size
The total size of the chunk in bytes.
Definition at line 122 of file ArenaAllocator.hpp.
Referenced by allocate(), canFit(), and getRemaining().
used
size_t ml::ArenaChunk::used
The amount of memory used in bytes.
Definition at line 127 of file ArenaAllocator.hpp.
Referenced by allocate(), getRemaining(), and getUnused().
The documentation for this struct was generated from the following file:
include/ml/Basic/ArenaAllocator.hpp