.TH "src/main.cpp" 3 "Version 0.0.0" "my-lang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Entry point of the My Language compiler\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Entry point of the My Language compiler\&. 
.PP
\fBReturns\fP
.RS 4
Exit code of the program\&. 
.RE
.PP

.PP
Definition at line \fB9\fP of file \fBmain\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for my-lang from the source code\&.
